/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetAccountsResponseV5 struct for GetAccountsResponseV5
type GetAccountsResponseV5 struct {
	NetLiquidation string `json:"netLiquidation,omitempty"`
	UnrealizedProfitLoss string `json:"unrealizedProfitLoss,omitempty"`
	UnrealizedProfitLossRate string `json:"unrealizedProfitLossRate,omitempty"`
	Currency string `json:"currency,omitempty"`
	CurrencyId float32 `json:"currencyId,omitempty"`
	Accounts []GetAccountsResponseV5Accounts `json:"accounts,omitempty"`
	Positions []map[string]interface{} `json:"positions,omitempty"`
	OpenOrders []map[string]interface{} `json:"openOrders,omitempty"`
	OpenOrderSize float32 `json:"openOrderSize,omitempty"`
	Positions2 []GetAccountsResponseV5Positions2 `json:"positions2,omitempty"`
	OpenOrders2 []map[string]interface{} `json:"openOrders2,omitempty"`
	OpenIpoOrders []map[string]interface{} `json:"openIpoOrders,omitempty"`
}
