/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetDividendsResponse struct for GetDividendsResponse
type GetDividendsResponse struct {
	DividendTotal string `json:"dividendTotal,omitempty"`
	HasTax bool `json:"hasTax,omitempty"`
}
