/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostLoginResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostLoginResponse{}

// PostLoginResponse struct for PostLoginResponse
type PostLoginResponse struct {
	AccessToken *string `json:"accessToken,omitempty"`
	ExtInfo *PostLoginResponseExtInfo `json:"extInfo,omitempty"`
	FirstTimeOfThird *bool `json:"firstTimeOfThird,omitempty"`
	RefreshToken *string `json:"refreshToken,omitempty"`
	RegisterAddress *int32 `json:"registerAddress,omitempty"`
	Settings *PostLoginResponseSettings `json:"settings,omitempty"`
	TokenExpireTime *string `json:"tokenExpireTime,omitempty"`
	Uuid *string `json:"uuid,omitempty"`
}

// NewPostLoginResponse instantiates a new PostLoginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostLoginResponse() *PostLoginResponse {
	this := PostLoginResponse{}
	return &this
}

// NewPostLoginResponseWithDefaults instantiates a new PostLoginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostLoginResponseWithDefaults() *PostLoginResponse {
	this := PostLoginResponse{}
	return &this
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *PostLoginResponse) GetAccessToken() string {
	if o == nil || IsNil(o.AccessToken) {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostLoginResponse) GetAccessTokenOk() (*string, bool) {
	if o == nil || IsNil(o.AccessToken) {
		return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *PostLoginResponse) HasAccessToken() bool {
	if o != nil && !IsNil(o.AccessToken) {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *PostLoginResponse) SetAccessToken(v string) {
	o.AccessToken = &v
}

// GetExtInfo returns the ExtInfo field value if set, zero value otherwise.
func (o *PostLoginResponse) GetExtInfo() PostLoginResponseExtInfo {
	if o == nil || IsNil(o.ExtInfo) {
		var ret PostLoginResponseExtInfo
		return ret
	}
	return *o.ExtInfo
}

// GetExtInfoOk returns a tuple with the ExtInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostLoginResponse) GetExtInfoOk() (*PostLoginResponseExtInfo, bool) {
	if o == nil || IsNil(o.ExtInfo) {
		return nil, false
	}
	return o.ExtInfo, true
}

// HasExtInfo returns a boolean if a field has been set.
func (o *PostLoginResponse) HasExtInfo() bool {
	if o != nil && !IsNil(o.ExtInfo) {
		return true
	}

	return false
}

// SetExtInfo gets a reference to the given PostLoginResponseExtInfo and assigns it to the ExtInfo field.
func (o *PostLoginResponse) SetExtInfo(v PostLoginResponseExtInfo) {
	o.ExtInfo = &v
}

// GetFirstTimeOfThird returns the FirstTimeOfThird field value if set, zero value otherwise.
func (o *PostLoginResponse) GetFirstTimeOfThird() bool {
	if o == nil || IsNil(o.FirstTimeOfThird) {
		var ret bool
		return ret
	}
	return *o.FirstTimeOfThird
}

// GetFirstTimeOfThirdOk returns a tuple with the FirstTimeOfThird field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostLoginResponse) GetFirstTimeOfThirdOk() (*bool, bool) {
	if o == nil || IsNil(o.FirstTimeOfThird) {
		return nil, false
	}
	return o.FirstTimeOfThird, true
}

// HasFirstTimeOfThird returns a boolean if a field has been set.
func (o *PostLoginResponse) HasFirstTimeOfThird() bool {
	if o != nil && !IsNil(o.FirstTimeOfThird) {
		return true
	}

	return false
}

// SetFirstTimeOfThird gets a reference to the given bool and assigns it to the FirstTimeOfThird field.
func (o *PostLoginResponse) SetFirstTimeOfThird(v bool) {
	o.FirstTimeOfThird = &v
}

// GetRefreshToken returns the RefreshToken field value if set, zero value otherwise.
func (o *PostLoginResponse) GetRefreshToken() string {
	if o == nil || IsNil(o.RefreshToken) {
		var ret string
		return ret
	}
	return *o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostLoginResponse) GetRefreshTokenOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshToken) {
		return nil, false
	}
	return o.RefreshToken, true
}

// HasRefreshToken returns a boolean if a field has been set.
func (o *PostLoginResponse) HasRefreshToken() bool {
	if o != nil && !IsNil(o.RefreshToken) {
		return true
	}

	return false
}

// SetRefreshToken gets a reference to the given string and assigns it to the RefreshToken field.
func (o *PostLoginResponse) SetRefreshToken(v string) {
	o.RefreshToken = &v
}

// GetRegisterAddress returns the RegisterAddress field value if set, zero value otherwise.
func (o *PostLoginResponse) GetRegisterAddress() int32 {
	if o == nil || IsNil(o.RegisterAddress) {
		var ret int32
		return ret
	}
	return *o.RegisterAddress
}

// GetRegisterAddressOk returns a tuple with the RegisterAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostLoginResponse) GetRegisterAddressOk() (*int32, bool) {
	if o == nil || IsNil(o.RegisterAddress) {
		return nil, false
	}
	return o.RegisterAddress, true
}

// HasRegisterAddress returns a boolean if a field has been set.
func (o *PostLoginResponse) HasRegisterAddress() bool {
	if o != nil && !IsNil(o.RegisterAddress) {
		return true
	}

	return false
}

// SetRegisterAddress gets a reference to the given int32 and assigns it to the RegisterAddress field.
func (o *PostLoginResponse) SetRegisterAddress(v int32) {
	o.RegisterAddress = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *PostLoginResponse) GetSettings() PostLoginResponseSettings {
	if o == nil || IsNil(o.Settings) {
		var ret PostLoginResponseSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostLoginResponse) GetSettingsOk() (*PostLoginResponseSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *PostLoginResponse) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given PostLoginResponseSettings and assigns it to the Settings field.
func (o *PostLoginResponse) SetSettings(v PostLoginResponseSettings) {
	o.Settings = &v
}

// GetTokenExpireTime returns the TokenExpireTime field value if set, zero value otherwise.
func (o *PostLoginResponse) GetTokenExpireTime() string {
	if o == nil || IsNil(o.TokenExpireTime) {
		var ret string
		return ret
	}
	return *o.TokenExpireTime
}

// GetTokenExpireTimeOk returns a tuple with the TokenExpireTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostLoginResponse) GetTokenExpireTimeOk() (*string, bool) {
	if o == nil || IsNil(o.TokenExpireTime) {
		return nil, false
	}
	return o.TokenExpireTime, true
}

// HasTokenExpireTime returns a boolean if a field has been set.
func (o *PostLoginResponse) HasTokenExpireTime() bool {
	if o != nil && !IsNil(o.TokenExpireTime) {
		return true
	}

	return false
}

// SetTokenExpireTime gets a reference to the given string and assigns it to the TokenExpireTime field.
func (o *PostLoginResponse) SetTokenExpireTime(v string) {
	o.TokenExpireTime = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *PostLoginResponse) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostLoginResponse) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *PostLoginResponse) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *PostLoginResponse) SetUuid(v string) {
	o.Uuid = &v
}

func (o PostLoginResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostLoginResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessToken) {
		toSerialize["accessToken"] = o.AccessToken
	}
	if !IsNil(o.ExtInfo) {
		toSerialize["extInfo"] = o.ExtInfo
	}
	if !IsNil(o.FirstTimeOfThird) {
		toSerialize["firstTimeOfThird"] = o.FirstTimeOfThird
	}
	if !IsNil(o.RefreshToken) {
		toSerialize["refreshToken"] = o.RefreshToken
	}
	if !IsNil(o.RegisterAddress) {
		toSerialize["registerAddress"] = o.RegisterAddress
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.TokenExpireTime) {
		toSerialize["tokenExpireTime"] = o.TokenExpireTime
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	return toSerialize, nil
}

type NullablePostLoginResponse struct {
	value *PostLoginResponse
	isSet bool
}

func (v NullablePostLoginResponse) Get() *PostLoginResponse {
	return v.value
}

func (v *NullablePostLoginResponse) Set(val *PostLoginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostLoginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostLoginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostLoginResponse(val *PostLoginResponse) *NullablePostLoginResponse {
	return &NullablePostLoginResponse{value: val, isSet: true}
}

func (v NullablePostLoginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostLoginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


