/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetTickerChartRequest struct for GetTickerChartRequest
type GetTickerChartRequest struct {
	// Number of bars to return
	Count string `json:"count,omitempty"`
	// Whether to include pre-market and afterhours bars. '1' is used for pre-market and after-hours bars.
	ExtendTrading int32 `json:"extendTrading,omitempty"`
	Type string `json:"type,omitempty"`
}
