/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAcccountRequestBannersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAcccountRequestBannersInner{}

// GetAcccountRequestBannersInner struct for GetAcccountRequestBannersInner
type GetAcccountRequestBannersInner struct {
	ImgUrl *string `json:"imgUrl,omitempty"`
	Link *string `json:"link,omitempty"`
	SubTitle *string `json:"subTitle,omitempty"`
	Title *string `json:"title,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewGetAcccountRequestBannersInner instantiates a new GetAcccountRequestBannersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAcccountRequestBannersInner() *GetAcccountRequestBannersInner {
	this := GetAcccountRequestBannersInner{}
	return &this
}

// NewGetAcccountRequestBannersInnerWithDefaults instantiates a new GetAcccountRequestBannersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAcccountRequestBannersInnerWithDefaults() *GetAcccountRequestBannersInner {
	this := GetAcccountRequestBannersInner{}
	return &this
}

// GetImgUrl returns the ImgUrl field value if set, zero value otherwise.
func (o *GetAcccountRequestBannersInner) GetImgUrl() string {
	if o == nil || IsNil(o.ImgUrl) {
		var ret string
		return ret
	}
	return *o.ImgUrl
}

// GetImgUrlOk returns a tuple with the ImgUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestBannersInner) GetImgUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImgUrl) {
		return nil, false
	}
	return o.ImgUrl, true
}

// HasImgUrl returns a boolean if a field has been set.
func (o *GetAcccountRequestBannersInner) HasImgUrl() bool {
	if o != nil && !IsNil(o.ImgUrl) {
		return true
	}

	return false
}

// SetImgUrl gets a reference to the given string and assigns it to the ImgUrl field.
func (o *GetAcccountRequestBannersInner) SetImgUrl(v string) {
	o.ImgUrl = &v
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *GetAcccountRequestBannersInner) GetLink() string {
	if o == nil || IsNil(o.Link) {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestBannersInner) GetLinkOk() (*string, bool) {
	if o == nil || IsNil(o.Link) {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *GetAcccountRequestBannersInner) HasLink() bool {
	if o != nil && !IsNil(o.Link) {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *GetAcccountRequestBannersInner) SetLink(v string) {
	o.Link = &v
}

// GetSubTitle returns the SubTitle field value if set, zero value otherwise.
func (o *GetAcccountRequestBannersInner) GetSubTitle() string {
	if o == nil || IsNil(o.SubTitle) {
		var ret string
		return ret
	}
	return *o.SubTitle
}

// GetSubTitleOk returns a tuple with the SubTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestBannersInner) GetSubTitleOk() (*string, bool) {
	if o == nil || IsNil(o.SubTitle) {
		return nil, false
	}
	return o.SubTitle, true
}

// HasSubTitle returns a boolean if a field has been set.
func (o *GetAcccountRequestBannersInner) HasSubTitle() bool {
	if o != nil && !IsNil(o.SubTitle) {
		return true
	}

	return false
}

// SetSubTitle gets a reference to the given string and assigns it to the SubTitle field.
func (o *GetAcccountRequestBannersInner) SetSubTitle(v string) {
	o.SubTitle = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetAcccountRequestBannersInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestBannersInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetAcccountRequestBannersInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetAcccountRequestBannersInner) SetTitle(v string) {
	o.Title = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetAcccountRequestBannersInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestBannersInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetAcccountRequestBannersInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetAcccountRequestBannersInner) SetType(v string) {
	o.Type = &v
}

func (o GetAcccountRequestBannersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAcccountRequestBannersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ImgUrl) {
		toSerialize["imgUrl"] = o.ImgUrl
	}
	if !IsNil(o.Link) {
		toSerialize["link"] = o.Link
	}
	if !IsNil(o.SubTitle) {
		toSerialize["subTitle"] = o.SubTitle
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableGetAcccountRequestBannersInner struct {
	value *GetAcccountRequestBannersInner
	isSet bool
}

func (v NullableGetAcccountRequestBannersInner) Get() *GetAcccountRequestBannersInner {
	return v.value
}

func (v *NullableGetAcccountRequestBannersInner) Set(val *GetAcccountRequestBannersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAcccountRequestBannersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAcccountRequestBannersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAcccountRequestBannersInner(val *GetAcccountRequestBannersInner) *NullableGetAcccountRequestBannersInner {
	return &NullableGetAcccountRequestBannersInner{value: val, isSet: true}
}

func (v NullableGetAcccountRequestBannersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAcccountRequestBannersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


