/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetIsTradeableResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIsTradeableResponse{}

// GetIsTradeableResponse struct for GetIsTradeableResponse
type GetIsTradeableResponse struct {
	Data []GetIsTradeableResponseDataInner `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// NewGetIsTradeableResponse instantiates a new GetIsTradeableResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIsTradeableResponse() *GetIsTradeableResponse {
	this := GetIsTradeableResponse{}
	return &this
}

// NewGetIsTradeableResponseWithDefaults instantiates a new GetIsTradeableResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIsTradeableResponseWithDefaults() *GetIsTradeableResponse {
	this := GetIsTradeableResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetIsTradeableResponse) GetData() []GetIsTradeableResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetIsTradeableResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIsTradeableResponse) GetDataOk() ([]GetIsTradeableResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetIsTradeableResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetIsTradeableResponseDataInner and assigns it to the Data field.
func (o *GetIsTradeableResponse) SetData(v []GetIsTradeableResponseDataInner) {
	o.Data = v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetIsTradeableResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIsTradeableResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetIsTradeableResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetIsTradeableResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o GetIsTradeableResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIsTradeableResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableGetIsTradeableResponse struct {
	value *GetIsTradeableResponse
	isSet bool
}

func (v NullableGetIsTradeableResponse) Get() *GetIsTradeableResponse {
	return v.value
}

func (v *NullableGetIsTradeableResponse) Set(val *GetIsTradeableResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIsTradeableResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIsTradeableResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIsTradeableResponse(val *GetIsTradeableResponse) *NullableGetIsTradeableResponse {
	return &NullableGetIsTradeableResponse{value: val, isSet: true}
}

func (v NullableGetIsTradeableResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIsTradeableResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


