/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetAcccountRequestBanners struct for GetAcccountRequestBanners
type GetAcccountRequestBanners struct {
	ImgUrl string `json:"imgUrl,omitempty"`
	Link string `json:"link,omitempty"`
	SubTitle string `json:"subTitle,omitempty"`
	Title string `json:"title,omitempty"`
	Type string `json:"type,omitempty"`
}
