/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetUserDetailsResponse struct for GetUserDetailsResponse
type GetUserDetailsResponse struct {
	AvatarUrl string `json:"avatarUrl,omitempty"`
	Email string `json:"email,omitempty"`
	NickName string `json:"nickName,omitempty"`
	PwdFlag int32 `json:"pwdFlag,omitempty"`
	RegionId int32 `json:"regionId,omitempty"`
	RegionName string `json:"regionName,omitempty"`
	Sex int32 `json:"sex,omitempty"`
	ThirdAccounts []map[string]interface{} `json:"thirdAccounts,omitempty"`
	TradeLockemail string `json:"tradeLockemail,omitempty"`
	Uuid string `json:"uuid,omitempty"`
}
