/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetAlertsResponseTickerWarning struct for GetAlertsResponseTickerWarning
type GetAlertsResponseTickerWarning struct {
	BizTimestamp float32 `json:"bizTimestamp,omitempty"`
	Del bool `json:"del,omitempty"`
	DisExchangeCode string `json:"disExchangeCode,omitempty"`
	DisSymbol string `json:"disSymbol,omitempty"`
	ExchangeCode string `json:"exchangeCode,omitempty"`
	ExchangeTrade bool `json:"exchangeTrade,omitempty"`
	RegionId int32 `json:"regionId,omitempty"`
	Rules []GetAlertsResponseTickerWarningRules `json:"rules,omitempty"`
	ShowCode string `json:"showCode,omitempty"`
	TickerId int32 `json:"tickerId,omitempty"`
	TickerName string `json:"tickerName,omitempty"`
	TickerSymbol string `json:"tickerSymbol,omitempty"`
	TickerType int32 `json:"tickerType,omitempty"`
	TinyName string `json:"tinyName,omitempty"`
	UpdateTime string `json:"updateTime,omitempty"`
	WarningFrequency int32 `json:"warningFrequency,omitempty"`
	WarningInterval int32 `json:"warningInterval,omitempty"`
	WarningMode int32 `json:"warningMode,omitempty"`
}
