/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PostTradeTokenResponse struct for PostTradeTokenResponse
type PostTradeTokenResponse struct {
	Data PostTradeTokenResponseData `json:"data,omitempty"`
	Success bool `json:"success,omitempty"`
}
