/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAccountsResponseV5Positions2InnerPositionsInnerTicker type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccountsResponseV5Positions2InnerPositionsInnerTicker{}

// GetAccountsResponseV5Positions2InnerPositionsInnerTicker struct for GetAccountsResponseV5Positions2InnerPositionsInnerTicker
type GetAccountsResponseV5Positions2InnerPositionsInnerTicker struct {
	TickerId *float32 `json:"tickerId,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
	Name *string `json:"name,omitempty"`
	TinyName *string `json:"tinyName,omitempty"`
	ListStatus *float32 `json:"listStatus,omitempty"`
	ExchangeCode *string `json:"exchangeCode,omitempty"`
	ExchangeId *float32 `json:"exchangeId,omitempty"`
	ExtType []map[string]interface{} `json:"extType,omitempty"`
	Type *float32 `json:"type,omitempty"`
	RegionId *float32 `json:"regionId,omitempty"`
	RegionName *string `json:"regionName,omitempty"`
	RegionIsoCode *string `json:"regionIsoCode,omitempty"`
	CurrencyId *float32 `json:"currencyId,omitempty"`
	CurrencyCode *string `json:"currencyCode,omitempty"`
	SecType []float32 `json:"secType,omitempty"`
	DisExchangeCode *string `json:"disExchangeCode,omitempty"`
	DisSymbol *string `json:"disSymbol,omitempty"`
}

// NewGetAccountsResponseV5Positions2InnerPositionsInnerTicker instantiates a new GetAccountsResponseV5Positions2InnerPositionsInnerTicker object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountsResponseV5Positions2InnerPositionsInnerTicker() *GetAccountsResponseV5Positions2InnerPositionsInnerTicker {
	this := GetAccountsResponseV5Positions2InnerPositionsInnerTicker{}
	return &this
}

// NewGetAccountsResponseV5Positions2InnerPositionsInnerTickerWithDefaults instantiates a new GetAccountsResponseV5Positions2InnerPositionsInnerTicker object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountsResponseV5Positions2InnerPositionsInnerTickerWithDefaults() *GetAccountsResponseV5Positions2InnerPositionsInnerTicker {
	this := GetAccountsResponseV5Positions2InnerPositionsInnerTicker{}
	return &this
}

// GetTickerId returns the TickerId field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetTickerId() float32 {
	if o == nil || IsNil(o.TickerId) {
		var ret float32
		return ret
	}
	return *o.TickerId
}

// GetTickerIdOk returns a tuple with the TickerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetTickerIdOk() (*float32, bool) {
	if o == nil || IsNil(o.TickerId) {
		return nil, false
	}
	return o.TickerId, true
}

// HasTickerId returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasTickerId() bool {
	if o != nil && !IsNil(o.TickerId) {
		return true
	}

	return false
}

// SetTickerId gets a reference to the given float32 and assigns it to the TickerId field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetTickerId(v float32) {
	o.TickerId = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetSymbol(v string) {
	o.Symbol = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetName(v string) {
	o.Name = &v
}

// GetTinyName returns the TinyName field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetTinyName() string {
	if o == nil || IsNil(o.TinyName) {
		var ret string
		return ret
	}
	return *o.TinyName
}

// GetTinyNameOk returns a tuple with the TinyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetTinyNameOk() (*string, bool) {
	if o == nil || IsNil(o.TinyName) {
		return nil, false
	}
	return o.TinyName, true
}

// HasTinyName returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasTinyName() bool {
	if o != nil && !IsNil(o.TinyName) {
		return true
	}

	return false
}

// SetTinyName gets a reference to the given string and assigns it to the TinyName field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetTinyName(v string) {
	o.TinyName = &v
}

// GetListStatus returns the ListStatus field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetListStatus() float32 {
	if o == nil || IsNil(o.ListStatus) {
		var ret float32
		return ret
	}
	return *o.ListStatus
}

// GetListStatusOk returns a tuple with the ListStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetListStatusOk() (*float32, bool) {
	if o == nil || IsNil(o.ListStatus) {
		return nil, false
	}
	return o.ListStatus, true
}

// HasListStatus returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasListStatus() bool {
	if o != nil && !IsNil(o.ListStatus) {
		return true
	}

	return false
}

// SetListStatus gets a reference to the given float32 and assigns it to the ListStatus field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetListStatus(v float32) {
	o.ListStatus = &v
}

// GetExchangeCode returns the ExchangeCode field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetExchangeCode() string {
	if o == nil || IsNil(o.ExchangeCode) {
		var ret string
		return ret
	}
	return *o.ExchangeCode
}

// GetExchangeCodeOk returns a tuple with the ExchangeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetExchangeCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ExchangeCode) {
		return nil, false
	}
	return o.ExchangeCode, true
}

// HasExchangeCode returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasExchangeCode() bool {
	if o != nil && !IsNil(o.ExchangeCode) {
		return true
	}

	return false
}

// SetExchangeCode gets a reference to the given string and assigns it to the ExchangeCode field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetExchangeCode(v string) {
	o.ExchangeCode = &v
}

// GetExchangeId returns the ExchangeId field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetExchangeId() float32 {
	if o == nil || IsNil(o.ExchangeId) {
		var ret float32
		return ret
	}
	return *o.ExchangeId
}

// GetExchangeIdOk returns a tuple with the ExchangeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetExchangeIdOk() (*float32, bool) {
	if o == nil || IsNil(o.ExchangeId) {
		return nil, false
	}
	return o.ExchangeId, true
}

// HasExchangeId returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasExchangeId() bool {
	if o != nil && !IsNil(o.ExchangeId) {
		return true
	}

	return false
}

// SetExchangeId gets a reference to the given float32 and assigns it to the ExchangeId field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetExchangeId(v float32) {
	o.ExchangeId = &v
}

// GetExtType returns the ExtType field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetExtType() []map[string]interface{} {
	if o == nil || IsNil(o.ExtType) {
		var ret []map[string]interface{}
		return ret
	}
	return o.ExtType
}

// GetExtTypeOk returns a tuple with the ExtType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetExtTypeOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExtType) {
		return nil, false
	}
	return o.ExtType, true
}

// HasExtType returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasExtType() bool {
	if o != nil && !IsNil(o.ExtType) {
		return true
	}

	return false
}

// SetExtType gets a reference to the given []map[string]interface{} and assigns it to the ExtType field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetExtType(v []map[string]interface{}) {
	o.ExtType = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetType() float32 {
	if o == nil || IsNil(o.Type) {
		var ret float32
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetTypeOk() (*float32, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given float32 and assigns it to the Type field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetType(v float32) {
	o.Type = &v
}

// GetRegionId returns the RegionId field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetRegionId() float32 {
	if o == nil || IsNil(o.RegionId) {
		var ret float32
		return ret
	}
	return *o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetRegionIdOk() (*float32, bool) {
	if o == nil || IsNil(o.RegionId) {
		return nil, false
	}
	return o.RegionId, true
}

// HasRegionId returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasRegionId() bool {
	if o != nil && !IsNil(o.RegionId) {
		return true
	}

	return false
}

// SetRegionId gets a reference to the given float32 and assigns it to the RegionId field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetRegionId(v float32) {
	o.RegionId = &v
}

// GetRegionName returns the RegionName field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetRegionName() string {
	if o == nil || IsNil(o.RegionName) {
		var ret string
		return ret
	}
	return *o.RegionName
}

// GetRegionNameOk returns a tuple with the RegionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetRegionNameOk() (*string, bool) {
	if o == nil || IsNil(o.RegionName) {
		return nil, false
	}
	return o.RegionName, true
}

// HasRegionName returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasRegionName() bool {
	if o != nil && !IsNil(o.RegionName) {
		return true
	}

	return false
}

// SetRegionName gets a reference to the given string and assigns it to the RegionName field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetRegionName(v string) {
	o.RegionName = &v
}

// GetRegionIsoCode returns the RegionIsoCode field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetRegionIsoCode() string {
	if o == nil || IsNil(o.RegionIsoCode) {
		var ret string
		return ret
	}
	return *o.RegionIsoCode
}

// GetRegionIsoCodeOk returns a tuple with the RegionIsoCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetRegionIsoCodeOk() (*string, bool) {
	if o == nil || IsNil(o.RegionIsoCode) {
		return nil, false
	}
	return o.RegionIsoCode, true
}

// HasRegionIsoCode returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasRegionIsoCode() bool {
	if o != nil && !IsNil(o.RegionIsoCode) {
		return true
	}

	return false
}

// SetRegionIsoCode gets a reference to the given string and assigns it to the RegionIsoCode field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetRegionIsoCode(v string) {
	o.RegionIsoCode = &v
}

// GetCurrencyId returns the CurrencyId field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetCurrencyId() float32 {
	if o == nil || IsNil(o.CurrencyId) {
		var ret float32
		return ret
	}
	return *o.CurrencyId
}

// GetCurrencyIdOk returns a tuple with the CurrencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetCurrencyIdOk() (*float32, bool) {
	if o == nil || IsNil(o.CurrencyId) {
		return nil, false
	}
	return o.CurrencyId, true
}

// HasCurrencyId returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasCurrencyId() bool {
	if o != nil && !IsNil(o.CurrencyId) {
		return true
	}

	return false
}

// SetCurrencyId gets a reference to the given float32 and assigns it to the CurrencyId field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetCurrencyId(v float32) {
	o.CurrencyId = &v
}

// GetCurrencyCode returns the CurrencyCode field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetCurrencyCode() string {
	if o == nil || IsNil(o.CurrencyCode) {
		var ret string
		return ret
	}
	return *o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyCode) {
		return nil, false
	}
	return o.CurrencyCode, true
}

// HasCurrencyCode returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasCurrencyCode() bool {
	if o != nil && !IsNil(o.CurrencyCode) {
		return true
	}

	return false
}

// SetCurrencyCode gets a reference to the given string and assigns it to the CurrencyCode field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetCurrencyCode(v string) {
	o.CurrencyCode = &v
}

// GetSecType returns the SecType field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetSecType() []float32 {
	if o == nil || IsNil(o.SecType) {
		var ret []float32
		return ret
	}
	return o.SecType
}

// GetSecTypeOk returns a tuple with the SecType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetSecTypeOk() ([]float32, bool) {
	if o == nil || IsNil(o.SecType) {
		return nil, false
	}
	return o.SecType, true
}

// HasSecType returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasSecType() bool {
	if o != nil && !IsNil(o.SecType) {
		return true
	}

	return false
}

// SetSecType gets a reference to the given []float32 and assigns it to the SecType field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetSecType(v []float32) {
	o.SecType = v
}

// GetDisExchangeCode returns the DisExchangeCode field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetDisExchangeCode() string {
	if o == nil || IsNil(o.DisExchangeCode) {
		var ret string
		return ret
	}
	return *o.DisExchangeCode
}

// GetDisExchangeCodeOk returns a tuple with the DisExchangeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetDisExchangeCodeOk() (*string, bool) {
	if o == nil || IsNil(o.DisExchangeCode) {
		return nil, false
	}
	return o.DisExchangeCode, true
}

// HasDisExchangeCode returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasDisExchangeCode() bool {
	if o != nil && !IsNil(o.DisExchangeCode) {
		return true
	}

	return false
}

// SetDisExchangeCode gets a reference to the given string and assigns it to the DisExchangeCode field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetDisExchangeCode(v string) {
	o.DisExchangeCode = &v
}

// GetDisSymbol returns the DisSymbol field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetDisSymbol() string {
	if o == nil || IsNil(o.DisSymbol) {
		var ret string
		return ret
	}
	return *o.DisSymbol
}

// GetDisSymbolOk returns a tuple with the DisSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) GetDisSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.DisSymbol) {
		return nil, false
	}
	return o.DisSymbol, true
}

// HasDisSymbol returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) HasDisSymbol() bool {
	if o != nil && !IsNil(o.DisSymbol) {
		return true
	}

	return false
}

// SetDisSymbol gets a reference to the given string and assigns it to the DisSymbol field.
func (o *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) SetDisSymbol(v string) {
	o.DisSymbol = &v
}

func (o GetAccountsResponseV5Positions2InnerPositionsInnerTicker) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAccountsResponseV5Positions2InnerPositionsInnerTicker) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TickerId) {
		toSerialize["tickerId"] = o.TickerId
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TinyName) {
		toSerialize["tinyName"] = o.TinyName
	}
	if !IsNil(o.ListStatus) {
		toSerialize["listStatus"] = o.ListStatus
	}
	if !IsNil(o.ExchangeCode) {
		toSerialize["exchangeCode"] = o.ExchangeCode
	}
	if !IsNil(o.ExchangeId) {
		toSerialize["exchangeId"] = o.ExchangeId
	}
	if !IsNil(o.ExtType) {
		toSerialize["extType"] = o.ExtType
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.RegionId) {
		toSerialize["regionId"] = o.RegionId
	}
	if !IsNil(o.RegionName) {
		toSerialize["regionName"] = o.RegionName
	}
	if !IsNil(o.RegionIsoCode) {
		toSerialize["regionIsoCode"] = o.RegionIsoCode
	}
	if !IsNil(o.CurrencyId) {
		toSerialize["currencyId"] = o.CurrencyId
	}
	if !IsNil(o.CurrencyCode) {
		toSerialize["currencyCode"] = o.CurrencyCode
	}
	if !IsNil(o.SecType) {
		toSerialize["secType"] = o.SecType
	}
	if !IsNil(o.DisExchangeCode) {
		toSerialize["disExchangeCode"] = o.DisExchangeCode
	}
	if !IsNil(o.DisSymbol) {
		toSerialize["disSymbol"] = o.DisSymbol
	}
	return toSerialize, nil
}

type NullableGetAccountsResponseV5Positions2InnerPositionsInnerTicker struct {
	value *GetAccountsResponseV5Positions2InnerPositionsInnerTicker
	isSet bool
}

func (v NullableGetAccountsResponseV5Positions2InnerPositionsInnerTicker) Get() *GetAccountsResponseV5Positions2InnerPositionsInnerTicker {
	return v.value
}

func (v *NullableGetAccountsResponseV5Positions2InnerPositionsInnerTicker) Set(val *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountsResponseV5Positions2InnerPositionsInnerTicker) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountsResponseV5Positions2InnerPositionsInnerTicker) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountsResponseV5Positions2InnerPositionsInnerTicker(val *GetAccountsResponseV5Positions2InnerPositionsInnerTicker) *NullableGetAccountsResponseV5Positions2InnerPositionsInnerTicker {
	return &NullableGetAccountsResponseV5Positions2InnerPositionsInnerTicker{value: val, isSet: true}
}

func (v NullableGetAccountsResponseV5Positions2InnerPositionsInnerTicker) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountsResponseV5Positions2InnerPositionsInnerTicker) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


