/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetFundamentalsResponseForecastInnerDataPointsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFundamentalsResponseForecastInnerDataPointsInner{}

// GetFundamentalsResponseForecastInnerDataPointsInner struct for GetFundamentalsResponseForecastInnerDataPointsInner
type GetFundamentalsResponseForecastInnerDataPointsInner struct {
	ValueActual *int32 `json:"valueActual,omitempty"`
	ValueForecast *int32 `json:"valueForecast,omitempty"`
	XAxis *string `json:"xAxis,omitempty"`
}

// NewGetFundamentalsResponseForecastInnerDataPointsInner instantiates a new GetFundamentalsResponseForecastInnerDataPointsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFundamentalsResponseForecastInnerDataPointsInner() *GetFundamentalsResponseForecastInnerDataPointsInner {
	this := GetFundamentalsResponseForecastInnerDataPointsInner{}
	return &this
}

// NewGetFundamentalsResponseForecastInnerDataPointsInnerWithDefaults instantiates a new GetFundamentalsResponseForecastInnerDataPointsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFundamentalsResponseForecastInnerDataPointsInnerWithDefaults() *GetFundamentalsResponseForecastInnerDataPointsInner {
	this := GetFundamentalsResponseForecastInnerDataPointsInner{}
	return &this
}

// GetValueActual returns the ValueActual field value if set, zero value otherwise.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) GetValueActual() int32 {
	if o == nil || IsNil(o.ValueActual) {
		var ret int32
		return ret
	}
	return *o.ValueActual
}

// GetValueActualOk returns a tuple with the ValueActual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) GetValueActualOk() (*int32, bool) {
	if o == nil || IsNil(o.ValueActual) {
		return nil, false
	}
	return o.ValueActual, true
}

// HasValueActual returns a boolean if a field has been set.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) HasValueActual() bool {
	if o != nil && !IsNil(o.ValueActual) {
		return true
	}

	return false
}

// SetValueActual gets a reference to the given int32 and assigns it to the ValueActual field.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) SetValueActual(v int32) {
	o.ValueActual = &v
}

// GetValueForecast returns the ValueForecast field value if set, zero value otherwise.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) GetValueForecast() int32 {
	if o == nil || IsNil(o.ValueForecast) {
		var ret int32
		return ret
	}
	return *o.ValueForecast
}

// GetValueForecastOk returns a tuple with the ValueForecast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) GetValueForecastOk() (*int32, bool) {
	if o == nil || IsNil(o.ValueForecast) {
		return nil, false
	}
	return o.ValueForecast, true
}

// HasValueForecast returns a boolean if a field has been set.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) HasValueForecast() bool {
	if o != nil && !IsNil(o.ValueForecast) {
		return true
	}

	return false
}

// SetValueForecast gets a reference to the given int32 and assigns it to the ValueForecast field.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) SetValueForecast(v int32) {
	o.ValueForecast = &v
}

// GetXAxis returns the XAxis field value if set, zero value otherwise.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) GetXAxis() string {
	if o == nil || IsNil(o.XAxis) {
		var ret string
		return ret
	}
	return *o.XAxis
}

// GetXAxisOk returns a tuple with the XAxis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) GetXAxisOk() (*string, bool) {
	if o == nil || IsNil(o.XAxis) {
		return nil, false
	}
	return o.XAxis, true
}

// HasXAxis returns a boolean if a field has been set.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) HasXAxis() bool {
	if o != nil && !IsNil(o.XAxis) {
		return true
	}

	return false
}

// SetXAxis gets a reference to the given string and assigns it to the XAxis field.
func (o *GetFundamentalsResponseForecastInnerDataPointsInner) SetXAxis(v string) {
	o.XAxis = &v
}

func (o GetFundamentalsResponseForecastInnerDataPointsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFundamentalsResponseForecastInnerDataPointsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ValueActual) {
		toSerialize["valueActual"] = o.ValueActual
	}
	if !IsNil(o.ValueForecast) {
		toSerialize["valueForecast"] = o.ValueForecast
	}
	if !IsNil(o.XAxis) {
		toSerialize["xAxis"] = o.XAxis
	}
	return toSerialize, nil
}

type NullableGetFundamentalsResponseForecastInnerDataPointsInner struct {
	value *GetFundamentalsResponseForecastInnerDataPointsInner
	isSet bool
}

func (v NullableGetFundamentalsResponseForecastInnerDataPointsInner) Get() *GetFundamentalsResponseForecastInnerDataPointsInner {
	return v.value
}

func (v *NullableGetFundamentalsResponseForecastInnerDataPointsInner) Set(val *GetFundamentalsResponseForecastInnerDataPointsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFundamentalsResponseForecastInnerDataPointsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFundamentalsResponseForecastInnerDataPointsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFundamentalsResponseForecastInnerDataPointsInner(val *GetFundamentalsResponseForecastInnerDataPointsInner) *NullableGetFundamentalsResponseForecastInnerDataPointsInner {
	return &NullableGetFundamentalsResponseForecastInnerDataPointsInner{value: val, isSet: true}
}

func (v NullableGetFundamentalsResponseForecastInnerDataPointsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFundamentalsResponseForecastInnerDataPointsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


