/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetFundamentalsResponseRemind type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFundamentalsResponseRemind{}

// GetFundamentalsResponseRemind struct for GetFundamentalsResponseRemind
type GetFundamentalsResponseRemind struct {
	EstimateEarningsDate *string `json:"estimateEarningsDate,omitempty"`
	OpeningTime *string `json:"openingTime,omitempty"`
	ProjEps *string `json:"projEps,omitempty"`
}

// NewGetFundamentalsResponseRemind instantiates a new GetFundamentalsResponseRemind object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFundamentalsResponseRemind() *GetFundamentalsResponseRemind {
	this := GetFundamentalsResponseRemind{}
	return &this
}

// NewGetFundamentalsResponseRemindWithDefaults instantiates a new GetFundamentalsResponseRemind object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFundamentalsResponseRemindWithDefaults() *GetFundamentalsResponseRemind {
	this := GetFundamentalsResponseRemind{}
	return &this
}

// GetEstimateEarningsDate returns the EstimateEarningsDate field value if set, zero value otherwise.
func (o *GetFundamentalsResponseRemind) GetEstimateEarningsDate() string {
	if o == nil || IsNil(o.EstimateEarningsDate) {
		var ret string
		return ret
	}
	return *o.EstimateEarningsDate
}

// GetEstimateEarningsDateOk returns a tuple with the EstimateEarningsDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseRemind) GetEstimateEarningsDateOk() (*string, bool) {
	if o == nil || IsNil(o.EstimateEarningsDate) {
		return nil, false
	}
	return o.EstimateEarningsDate, true
}

// HasEstimateEarningsDate returns a boolean if a field has been set.
func (o *GetFundamentalsResponseRemind) HasEstimateEarningsDate() bool {
	if o != nil && !IsNil(o.EstimateEarningsDate) {
		return true
	}

	return false
}

// SetEstimateEarningsDate gets a reference to the given string and assigns it to the EstimateEarningsDate field.
func (o *GetFundamentalsResponseRemind) SetEstimateEarningsDate(v string) {
	o.EstimateEarningsDate = &v
}

// GetOpeningTime returns the OpeningTime field value if set, zero value otherwise.
func (o *GetFundamentalsResponseRemind) GetOpeningTime() string {
	if o == nil || IsNil(o.OpeningTime) {
		var ret string
		return ret
	}
	return *o.OpeningTime
}

// GetOpeningTimeOk returns a tuple with the OpeningTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseRemind) GetOpeningTimeOk() (*string, bool) {
	if o == nil || IsNil(o.OpeningTime) {
		return nil, false
	}
	return o.OpeningTime, true
}

// HasOpeningTime returns a boolean if a field has been set.
func (o *GetFundamentalsResponseRemind) HasOpeningTime() bool {
	if o != nil && !IsNil(o.OpeningTime) {
		return true
	}

	return false
}

// SetOpeningTime gets a reference to the given string and assigns it to the OpeningTime field.
func (o *GetFundamentalsResponseRemind) SetOpeningTime(v string) {
	o.OpeningTime = &v
}

// GetProjEps returns the ProjEps field value if set, zero value otherwise.
func (o *GetFundamentalsResponseRemind) GetProjEps() string {
	if o == nil || IsNil(o.ProjEps) {
		var ret string
		return ret
	}
	return *o.ProjEps
}

// GetProjEpsOk returns a tuple with the ProjEps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseRemind) GetProjEpsOk() (*string, bool) {
	if o == nil || IsNil(o.ProjEps) {
		return nil, false
	}
	return o.ProjEps, true
}

// HasProjEps returns a boolean if a field has been set.
func (o *GetFundamentalsResponseRemind) HasProjEps() bool {
	if o != nil && !IsNil(o.ProjEps) {
		return true
	}

	return false
}

// SetProjEps gets a reference to the given string and assigns it to the ProjEps field.
func (o *GetFundamentalsResponseRemind) SetProjEps(v string) {
	o.ProjEps = &v
}

func (o GetFundamentalsResponseRemind) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFundamentalsResponseRemind) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EstimateEarningsDate) {
		toSerialize["estimateEarningsDate"] = o.EstimateEarningsDate
	}
	if !IsNil(o.OpeningTime) {
		toSerialize["openingTime"] = o.OpeningTime
	}
	if !IsNil(o.ProjEps) {
		toSerialize["projEps"] = o.ProjEps
	}
	return toSerialize, nil
}

type NullableGetFundamentalsResponseRemind struct {
	value *GetFundamentalsResponseRemind
	isSet bool
}

func (v NullableGetFundamentalsResponseRemind) Get() *GetFundamentalsResponseRemind {
	return v.value
}

func (v *NullableGetFundamentalsResponseRemind) Set(val *GetFundamentalsResponseRemind) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFundamentalsResponseRemind) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFundamentalsResponseRemind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFundamentalsResponseRemind(val *GetFundamentalsResponseRemind) *NullableGetFundamentalsResponseRemind {
	return &NullableGetFundamentalsResponseRemind{value: val, isSet: true}
}

func (v NullableGetFundamentalsResponseRemind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFundamentalsResponseRemind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


