/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetTickerChartResponseDates struct for GetTickerChartResponseDates
type GetTickerChartResponseDates struct {
	End string `json:"end,omitempty"`
	Start string `json:"start,omitempty"`
	Type string `json:"type,omitempty"`
}
