/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ErrorBody struct for ErrorBody
type ErrorBody struct {
	Code string `json:"code,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
	Msg string `json:"msg,omitempty"`
	Success bool `json:"success,omitempty"`
	TraceId string `json:"traceId,omitempty"`
}
