/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetOrdersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrdersResponse{}

// GetOrdersResponse struct for GetOrdersResponse
type GetOrdersResponse struct {
	Data []GetOrdersItem `json:"data,omitempty"`
}

// NewGetOrdersResponse instantiates a new GetOrdersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrdersResponse() *GetOrdersResponse {
	this := GetOrdersResponse{}
	return &this
}

// NewGetOrdersResponseWithDefaults instantiates a new GetOrdersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrdersResponseWithDefaults() *GetOrdersResponse {
	this := GetOrdersResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetOrdersResponse) GetData() []GetOrdersItem {
	if o == nil || IsNil(o.Data) {
		var ret []GetOrdersItem
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersResponse) GetDataOk() ([]GetOrdersItem, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetOrdersResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetOrdersItem and assigns it to the Data field.
func (o *GetOrdersResponse) SetData(v []GetOrdersItem) {
	o.Data = v
}

func (o GetOrdersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrdersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetOrdersResponse struct {
	value *GetOrdersResponse
	isSet bool
}

func (v NullableGetOrdersResponse) Get() *GetOrdersResponse {
	return v.value
}

func (v *NullableGetOrdersResponse) Set(val *GetOrdersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrdersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrdersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrdersResponse(val *GetOrdersResponse) *NullableGetOrdersResponse {
	return &NullableGetOrdersResponse{value: val, isSet: true}
}

func (v NullableGetOrdersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrdersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


