/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAccountsResponseV5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccountsResponseV5{}

// GetAccountsResponseV5 struct for GetAccountsResponseV5
type GetAccountsResponseV5 struct {
	NetLiquidation *string `json:"netLiquidation,omitempty"`
	UnrealizedProfitLoss *string `json:"unrealizedProfitLoss,omitempty"`
	UnrealizedProfitLossRate *string `json:"unrealizedProfitLossRate,omitempty"`
	Currency *string `json:"currency,omitempty"`
	CurrencyId *float32 `json:"currencyId,omitempty"`
	Accounts []GetAccountsResponseV5AccountsInner `json:"accounts,omitempty"`
	Positions []map[string]interface{} `json:"positions,omitempty"`
	OpenOrders []map[string]interface{} `json:"openOrders,omitempty"`
	OpenOrderSize *float32 `json:"openOrderSize,omitempty"`
	Positions2 []GetAccountsResponseV5Positions2Inner `json:"positions2,omitempty"`
	OpenOrders2 []map[string]interface{} `json:"openOrders2,omitempty"`
	OpenIpoOrders []map[string]interface{} `json:"openIpoOrders,omitempty"`
}

// NewGetAccountsResponseV5 instantiates a new GetAccountsResponseV5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountsResponseV5() *GetAccountsResponseV5 {
	this := GetAccountsResponseV5{}
	return &this
}

// NewGetAccountsResponseV5WithDefaults instantiates a new GetAccountsResponseV5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountsResponseV5WithDefaults() *GetAccountsResponseV5 {
	this := GetAccountsResponseV5{}
	return &this
}

// GetNetLiquidation returns the NetLiquidation field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetNetLiquidation() string {
	if o == nil || IsNil(o.NetLiquidation) {
		var ret string
		return ret
	}
	return *o.NetLiquidation
}

// GetNetLiquidationOk returns a tuple with the NetLiquidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetNetLiquidationOk() (*string, bool) {
	if o == nil || IsNil(o.NetLiquidation) {
		return nil, false
	}
	return o.NetLiquidation, true
}

// HasNetLiquidation returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasNetLiquidation() bool {
	if o != nil && !IsNil(o.NetLiquidation) {
		return true
	}

	return false
}

// SetNetLiquidation gets a reference to the given string and assigns it to the NetLiquidation field.
func (o *GetAccountsResponseV5) SetNetLiquidation(v string) {
	o.NetLiquidation = &v
}

// GetUnrealizedProfitLoss returns the UnrealizedProfitLoss field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetUnrealizedProfitLoss() string {
	if o == nil || IsNil(o.UnrealizedProfitLoss) {
		var ret string
		return ret
	}
	return *o.UnrealizedProfitLoss
}

// GetUnrealizedProfitLossOk returns a tuple with the UnrealizedProfitLoss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetUnrealizedProfitLossOk() (*string, bool) {
	if o == nil || IsNil(o.UnrealizedProfitLoss) {
		return nil, false
	}
	return o.UnrealizedProfitLoss, true
}

// HasUnrealizedProfitLoss returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasUnrealizedProfitLoss() bool {
	if o != nil && !IsNil(o.UnrealizedProfitLoss) {
		return true
	}

	return false
}

// SetUnrealizedProfitLoss gets a reference to the given string and assigns it to the UnrealizedProfitLoss field.
func (o *GetAccountsResponseV5) SetUnrealizedProfitLoss(v string) {
	o.UnrealizedProfitLoss = &v
}

// GetUnrealizedProfitLossRate returns the UnrealizedProfitLossRate field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetUnrealizedProfitLossRate() string {
	if o == nil || IsNil(o.UnrealizedProfitLossRate) {
		var ret string
		return ret
	}
	return *o.UnrealizedProfitLossRate
}

// GetUnrealizedProfitLossRateOk returns a tuple with the UnrealizedProfitLossRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetUnrealizedProfitLossRateOk() (*string, bool) {
	if o == nil || IsNil(o.UnrealizedProfitLossRate) {
		return nil, false
	}
	return o.UnrealizedProfitLossRate, true
}

// HasUnrealizedProfitLossRate returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasUnrealizedProfitLossRate() bool {
	if o != nil && !IsNil(o.UnrealizedProfitLossRate) {
		return true
	}

	return false
}

// SetUnrealizedProfitLossRate gets a reference to the given string and assigns it to the UnrealizedProfitLossRate field.
func (o *GetAccountsResponseV5) SetUnrealizedProfitLossRate(v string) {
	o.UnrealizedProfitLossRate = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *GetAccountsResponseV5) SetCurrency(v string) {
	o.Currency = &v
}

// GetCurrencyId returns the CurrencyId field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetCurrencyId() float32 {
	if o == nil || IsNil(o.CurrencyId) {
		var ret float32
		return ret
	}
	return *o.CurrencyId
}

// GetCurrencyIdOk returns a tuple with the CurrencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetCurrencyIdOk() (*float32, bool) {
	if o == nil || IsNil(o.CurrencyId) {
		return nil, false
	}
	return o.CurrencyId, true
}

// HasCurrencyId returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasCurrencyId() bool {
	if o != nil && !IsNil(o.CurrencyId) {
		return true
	}

	return false
}

// SetCurrencyId gets a reference to the given float32 and assigns it to the CurrencyId field.
func (o *GetAccountsResponseV5) SetCurrencyId(v float32) {
	o.CurrencyId = &v
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetAccounts() []GetAccountsResponseV5AccountsInner {
	if o == nil || IsNil(o.Accounts) {
		var ret []GetAccountsResponseV5AccountsInner
		return ret
	}
	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetAccountsOk() ([]GetAccountsResponseV5AccountsInner, bool) {
	if o == nil || IsNil(o.Accounts) {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasAccounts() bool {
	if o != nil && !IsNil(o.Accounts) {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []GetAccountsResponseV5AccountsInner and assigns it to the Accounts field.
func (o *GetAccountsResponseV5) SetAccounts(v []GetAccountsResponseV5AccountsInner) {
	o.Accounts = v
}

// GetPositions returns the Positions field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetPositions() []map[string]interface{} {
	if o == nil || IsNil(o.Positions) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Positions
}

// GetPositionsOk returns a tuple with the Positions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetPositionsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Positions) {
		return nil, false
	}
	return o.Positions, true
}

// HasPositions returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasPositions() bool {
	if o != nil && !IsNil(o.Positions) {
		return true
	}

	return false
}

// SetPositions gets a reference to the given []map[string]interface{} and assigns it to the Positions field.
func (o *GetAccountsResponseV5) SetPositions(v []map[string]interface{}) {
	o.Positions = v
}

// GetOpenOrders returns the OpenOrders field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetOpenOrders() []map[string]interface{} {
	if o == nil || IsNil(o.OpenOrders) {
		var ret []map[string]interface{}
		return ret
	}
	return o.OpenOrders
}

// GetOpenOrdersOk returns a tuple with the OpenOrders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetOpenOrdersOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.OpenOrders) {
		return nil, false
	}
	return o.OpenOrders, true
}

// HasOpenOrders returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasOpenOrders() bool {
	if o != nil && !IsNil(o.OpenOrders) {
		return true
	}

	return false
}

// SetOpenOrders gets a reference to the given []map[string]interface{} and assigns it to the OpenOrders field.
func (o *GetAccountsResponseV5) SetOpenOrders(v []map[string]interface{}) {
	o.OpenOrders = v
}

// GetOpenOrderSize returns the OpenOrderSize field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetOpenOrderSize() float32 {
	if o == nil || IsNil(o.OpenOrderSize) {
		var ret float32
		return ret
	}
	return *o.OpenOrderSize
}

// GetOpenOrderSizeOk returns a tuple with the OpenOrderSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetOpenOrderSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.OpenOrderSize) {
		return nil, false
	}
	return o.OpenOrderSize, true
}

// HasOpenOrderSize returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasOpenOrderSize() bool {
	if o != nil && !IsNil(o.OpenOrderSize) {
		return true
	}

	return false
}

// SetOpenOrderSize gets a reference to the given float32 and assigns it to the OpenOrderSize field.
func (o *GetAccountsResponseV5) SetOpenOrderSize(v float32) {
	o.OpenOrderSize = &v
}

// GetPositions2 returns the Positions2 field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetPositions2() []GetAccountsResponseV5Positions2Inner {
	if o == nil || IsNil(o.Positions2) {
		var ret []GetAccountsResponseV5Positions2Inner
		return ret
	}
	return o.Positions2
}

// GetPositions2Ok returns a tuple with the Positions2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetPositions2Ok() ([]GetAccountsResponseV5Positions2Inner, bool) {
	if o == nil || IsNil(o.Positions2) {
		return nil, false
	}
	return o.Positions2, true
}

// HasPositions2 returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasPositions2() bool {
	if o != nil && !IsNil(o.Positions2) {
		return true
	}

	return false
}

// SetPositions2 gets a reference to the given []GetAccountsResponseV5Positions2Inner and assigns it to the Positions2 field.
func (o *GetAccountsResponseV5) SetPositions2(v []GetAccountsResponseV5Positions2Inner) {
	o.Positions2 = v
}

// GetOpenOrders2 returns the OpenOrders2 field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetOpenOrders2() []map[string]interface{} {
	if o == nil || IsNil(o.OpenOrders2) {
		var ret []map[string]interface{}
		return ret
	}
	return o.OpenOrders2
}

// GetOpenOrders2Ok returns a tuple with the OpenOrders2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetOpenOrders2Ok() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.OpenOrders2) {
		return nil, false
	}
	return o.OpenOrders2, true
}

// HasOpenOrders2 returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasOpenOrders2() bool {
	if o != nil && !IsNil(o.OpenOrders2) {
		return true
	}

	return false
}

// SetOpenOrders2 gets a reference to the given []map[string]interface{} and assigns it to the OpenOrders2 field.
func (o *GetAccountsResponseV5) SetOpenOrders2(v []map[string]interface{}) {
	o.OpenOrders2 = v
}

// GetOpenIpoOrders returns the OpenIpoOrders field value if set, zero value otherwise.
func (o *GetAccountsResponseV5) GetOpenIpoOrders() []map[string]interface{} {
	if o == nil || IsNil(o.OpenIpoOrders) {
		var ret []map[string]interface{}
		return ret
	}
	return o.OpenIpoOrders
}

// GetOpenIpoOrdersOk returns a tuple with the OpenIpoOrders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5) GetOpenIpoOrdersOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.OpenIpoOrders) {
		return nil, false
	}
	return o.OpenIpoOrders, true
}

// HasOpenIpoOrders returns a boolean if a field has been set.
func (o *GetAccountsResponseV5) HasOpenIpoOrders() bool {
	if o != nil && !IsNil(o.OpenIpoOrders) {
		return true
	}

	return false
}

// SetOpenIpoOrders gets a reference to the given []map[string]interface{} and assigns it to the OpenIpoOrders field.
func (o *GetAccountsResponseV5) SetOpenIpoOrders(v []map[string]interface{}) {
	o.OpenIpoOrders = v
}

func (o GetAccountsResponseV5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAccountsResponseV5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetLiquidation) {
		toSerialize["netLiquidation"] = o.NetLiquidation
	}
	if !IsNil(o.UnrealizedProfitLoss) {
		toSerialize["unrealizedProfitLoss"] = o.UnrealizedProfitLoss
	}
	if !IsNil(o.UnrealizedProfitLossRate) {
		toSerialize["unrealizedProfitLossRate"] = o.UnrealizedProfitLossRate
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.CurrencyId) {
		toSerialize["currencyId"] = o.CurrencyId
	}
	if !IsNil(o.Accounts) {
		toSerialize["accounts"] = o.Accounts
	}
	if !IsNil(o.Positions) {
		toSerialize["positions"] = o.Positions
	}
	if !IsNil(o.OpenOrders) {
		toSerialize["openOrders"] = o.OpenOrders
	}
	if !IsNil(o.OpenOrderSize) {
		toSerialize["openOrderSize"] = o.OpenOrderSize
	}
	if !IsNil(o.Positions2) {
		toSerialize["positions2"] = o.Positions2
	}
	if !IsNil(o.OpenOrders2) {
		toSerialize["openOrders2"] = o.OpenOrders2
	}
	if !IsNil(o.OpenIpoOrders) {
		toSerialize["openIpoOrders"] = o.OpenIpoOrders
	}
	return toSerialize, nil
}

type NullableGetAccountsResponseV5 struct {
	value *GetAccountsResponseV5
	isSet bool
}

func (v NullableGetAccountsResponseV5) Get() *GetAccountsResponseV5 {
	return v.value
}

func (v *NullableGetAccountsResponseV5) Set(val *GetAccountsResponseV5) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountsResponseV5) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountsResponseV5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountsResponseV5(val *GetAccountsResponseV5) *NullableGetAccountsResponseV5 {
	return &NullableGetAccountsResponseV5{value: val, isSet: true}
}

func (v NullableGetAccountsResponseV5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountsResponseV5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


