/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetAlertsResponseEventWarningRules struct for GetAlertsResponseEventWarningRules
type GetAlertsResponseEventWarningRules struct {
	Active string `json:"active,omitempty"`
	Type string `json:"type,omitempty"`
}
