/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Transfers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Transfers{}

// Transfers struct for Transfers
type Transfers struct {
	Success *bool `json:"success,omitempty"`
	Data []Transfer `json:"data,omitempty"`
}

// NewTransfers instantiates a new Transfers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransfers() *Transfers {
	this := Transfers{}
	return &this
}

// NewTransfersWithDefaults instantiates a new Transfers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransfersWithDefaults() *Transfers {
	this := Transfers{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *Transfers) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfers) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *Transfers) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *Transfers) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Transfers) GetData() []Transfer {
	if o == nil || IsNil(o.Data) {
		var ret []Transfer
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfers) GetDataOk() ([]Transfer, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Transfers) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Transfer and assigns it to the Data field.
func (o *Transfers) SetData(v []Transfer) {
	o.Data = v
}

func (o Transfers) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Transfers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableTransfers struct {
	value *Transfers
	isSet bool
}

func (v NullableTransfers) Get() *Transfers {
	return v.value
}

func (v *NullableTransfers) Set(val *Transfers) {
	v.value = val
	v.isSet = true
}

func (v NullableTransfers) IsSet() bool {
	return v.isSet
}

func (v *NullableTransfers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransfers(val *Transfers) *NullableTransfers {
	return &NullableTransfers{value: val, isSet: true}
}

func (v NullableTransfers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransfers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


