/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AccountInfo struct for AccountInfo
type AccountInfo struct {
	AccountType AccountType `json:"accountType,omitempty"`
	Currency string `json:"currency,omitempty"`
	NetLiquidation float32 `json:"netLiquidation,omitempty"`
	Pdt bool `json:"pdt,omitempty"`
	UnrealizedProfitLoss float32 `json:"unrealizedProfitLoss,omitempty"`
	UnrealizedProfitLossBase float32 `json:"unrealizedProfitLossBase,omitempty"`
	Warning bool `json:"warning,omitempty"`
}
