/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PostOtocoOrderRequest struct for PostOtocoOrderRequest
type PostOtocoOrderRequest struct {
	NewOrders []PostStockOrderRequest `json:"newOrders,omitempty"`
}
