/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ExecutionType the model 'ExecutionType'
type ExecutionType string

// List of ExecutionType
const (
	MARKET ExecutionType = "market"
	LIMIT ExecutionType = "limit"
)
