/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetAccountsResponseV5Positions struct for GetAccountsResponseV5Positions
type GetAccountsResponseV5Positions struct {
	PositionId float32 `json:"positionId,omitempty"`
	BrokerPosId string `json:"brokerPosId,omitempty"`
	BrokerId float32 `json:"brokerId,omitempty"`
	AssetType string `json:"assetType,omitempty"`
	TickerType string `json:"tickerType,omitempty"`
	Ticker GetAccountsResponseV5Ticker `json:"ticker,omitempty"`
	Action string `json:"action,omitempty"`
	Position string `json:"position,omitempty"`
	TickerId float32 `json:"tickerId,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	CostPrice string `json:"costPrice,omitempty"`
	Cost string `json:"cost,omitempty"`
	Currency string `json:"currency,omitempty"`
	MarketValue string `json:"marketValue,omitempty"`
	LastPrice string `json:"lastPrice,omitempty"`
	UnrealizedProfitLoss string `json:"unrealizedProfitLoss,omitempty"`
	UnrealizedProfitLossRate string `json:"unrealizedProfitLossRate,omitempty"`
	PositionProportion string `json:"positionProportion,omitempty"`
	UpdatePositionTime float32 `json:"updatePositionTime,omitempty"`
	OptionCanExercise float32 `json:"optionCanExercise,omitempty"`
	RecentlyExpireFlag bool `json:"recentlyExpireFlag,omitempty"`
	RemainDay float32 `json:"remainDay,omitempty"`
	IsLending string `json:"isLending,omitempty"`
}
