/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSecurityAccountsResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSecurityAccountsResponseDataInner{}

// GetSecurityAccountsResponseDataInner struct for GetSecurityAccountsResponseDataInner
type GetSecurityAccountsResponseDataInner struct {
	AccountTypes []string `json:"accountTypes,omitempty"`
	AllowDeposit *bool `json:"allowDeposit,omitempty"`
	BrokerAccountId *string `json:"brokerAccountId,omitempty"`
	BrokerId *int32 `json:"brokerId,omitempty"`
	BrokerName *string `json:"brokerName,omitempty"`
	ComboTypes []string `json:"comboTypes,omitempty"`
	CustomerType *string `json:"customerType,omitempty"`
	Deposit *bool `json:"deposit,omitempty"`
	DepositStatus *string `json:"depositStatus,omitempty"`
	GiftStockStatus *int32 `json:"giftStockStatus,omitempty"`
	IsDefault *bool `json:"isDefault,omitempty"`
	IsDefaultChecked *bool `json:"isDefaultChecked,omitempty"`
	OpenAccountUrl *string `json:"openAccountUrl,omitempty"`
	OptionOpenStatus *string `json:"optionOpenStatus,omitempty"`
	RegisterRegionId *int32 `json:"registerRegionId,omitempty"`
	RegisterTradeUrl *string `json:"registerTradeUrl,omitempty"`
	SecAccountId *int32 `json:"secAccountId,omitempty"`
	Status *string `json:"status,omitempty"`
	SupportClickIPO *bool `json:"supportClickIPO,omitempty"`
	SupportOpenOption *bool `json:"supportOpenOption,omitempty"`
	SupportOutsideRth *bool `json:"supportOutsideRth,omitempty"`
	TickerTypes []GetSecurityAccountsResponseDataInnerTickerTypesInner `json:"tickerTypes,omitempty"`
	TimeInForces []GetSecurityAccountsResponseDataInnerTimeInForcesInner `json:"timeInForces,omitempty"`
	UserTradePermissionVOs []GetSecurityAccountsResponseDataInnerUserTradePermissionVOsInner `json:"userTradePermissionVOs,omitempty"`
}

// NewGetSecurityAccountsResponseDataInner instantiates a new GetSecurityAccountsResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSecurityAccountsResponseDataInner() *GetSecurityAccountsResponseDataInner {
	this := GetSecurityAccountsResponseDataInner{}
	return &this
}

// NewGetSecurityAccountsResponseDataInnerWithDefaults instantiates a new GetSecurityAccountsResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSecurityAccountsResponseDataInnerWithDefaults() *GetSecurityAccountsResponseDataInner {
	this := GetSecurityAccountsResponseDataInner{}
	return &this
}

// GetAccountTypes returns the AccountTypes field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetAccountTypes() []string {
	if o == nil || IsNil(o.AccountTypes) {
		var ret []string
		return ret
	}
	return o.AccountTypes
}

// GetAccountTypesOk returns a tuple with the AccountTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetAccountTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.AccountTypes) {
		return nil, false
	}
	return o.AccountTypes, true
}

// HasAccountTypes returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasAccountTypes() bool {
	if o != nil && !IsNil(o.AccountTypes) {
		return true
	}

	return false
}

// SetAccountTypes gets a reference to the given []string and assigns it to the AccountTypes field.
func (o *GetSecurityAccountsResponseDataInner) SetAccountTypes(v []string) {
	o.AccountTypes = v
}

// GetAllowDeposit returns the AllowDeposit field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetAllowDeposit() bool {
	if o == nil || IsNil(o.AllowDeposit) {
		var ret bool
		return ret
	}
	return *o.AllowDeposit
}

// GetAllowDepositOk returns a tuple with the AllowDeposit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetAllowDepositOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowDeposit) {
		return nil, false
	}
	return o.AllowDeposit, true
}

// HasAllowDeposit returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasAllowDeposit() bool {
	if o != nil && !IsNil(o.AllowDeposit) {
		return true
	}

	return false
}

// SetAllowDeposit gets a reference to the given bool and assigns it to the AllowDeposit field.
func (o *GetSecurityAccountsResponseDataInner) SetAllowDeposit(v bool) {
	o.AllowDeposit = &v
}

// GetBrokerAccountId returns the BrokerAccountId field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetBrokerAccountId() string {
	if o == nil || IsNil(o.BrokerAccountId) {
		var ret string
		return ret
	}
	return *o.BrokerAccountId
}

// GetBrokerAccountIdOk returns a tuple with the BrokerAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetBrokerAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.BrokerAccountId) {
		return nil, false
	}
	return o.BrokerAccountId, true
}

// HasBrokerAccountId returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasBrokerAccountId() bool {
	if o != nil && !IsNil(o.BrokerAccountId) {
		return true
	}

	return false
}

// SetBrokerAccountId gets a reference to the given string and assigns it to the BrokerAccountId field.
func (o *GetSecurityAccountsResponseDataInner) SetBrokerAccountId(v string) {
	o.BrokerAccountId = &v
}

// GetBrokerId returns the BrokerId field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetBrokerId() int32 {
	if o == nil || IsNil(o.BrokerId) {
		var ret int32
		return ret
	}
	return *o.BrokerId
}

// GetBrokerIdOk returns a tuple with the BrokerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetBrokerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.BrokerId) {
		return nil, false
	}
	return o.BrokerId, true
}

// HasBrokerId returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasBrokerId() bool {
	if o != nil && !IsNil(o.BrokerId) {
		return true
	}

	return false
}

// SetBrokerId gets a reference to the given int32 and assigns it to the BrokerId field.
func (o *GetSecurityAccountsResponseDataInner) SetBrokerId(v int32) {
	o.BrokerId = &v
}

// GetBrokerName returns the BrokerName field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetBrokerName() string {
	if o == nil || IsNil(o.BrokerName) {
		var ret string
		return ret
	}
	return *o.BrokerName
}

// GetBrokerNameOk returns a tuple with the BrokerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetBrokerNameOk() (*string, bool) {
	if o == nil || IsNil(o.BrokerName) {
		return nil, false
	}
	return o.BrokerName, true
}

// HasBrokerName returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasBrokerName() bool {
	if o != nil && !IsNil(o.BrokerName) {
		return true
	}

	return false
}

// SetBrokerName gets a reference to the given string and assigns it to the BrokerName field.
func (o *GetSecurityAccountsResponseDataInner) SetBrokerName(v string) {
	o.BrokerName = &v
}

// GetComboTypes returns the ComboTypes field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetComboTypes() []string {
	if o == nil || IsNil(o.ComboTypes) {
		var ret []string
		return ret
	}
	return o.ComboTypes
}

// GetComboTypesOk returns a tuple with the ComboTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetComboTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.ComboTypes) {
		return nil, false
	}
	return o.ComboTypes, true
}

// HasComboTypes returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasComboTypes() bool {
	if o != nil && !IsNil(o.ComboTypes) {
		return true
	}

	return false
}

// SetComboTypes gets a reference to the given []string and assigns it to the ComboTypes field.
func (o *GetSecurityAccountsResponseDataInner) SetComboTypes(v []string) {
	o.ComboTypes = v
}

// GetCustomerType returns the CustomerType field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetCustomerType() string {
	if o == nil || IsNil(o.CustomerType) {
		var ret string
		return ret
	}
	return *o.CustomerType
}

// GetCustomerTypeOk returns a tuple with the CustomerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetCustomerTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerType) {
		return nil, false
	}
	return o.CustomerType, true
}

// HasCustomerType returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasCustomerType() bool {
	if o != nil && !IsNil(o.CustomerType) {
		return true
	}

	return false
}

// SetCustomerType gets a reference to the given string and assigns it to the CustomerType field.
func (o *GetSecurityAccountsResponseDataInner) SetCustomerType(v string) {
	o.CustomerType = &v
}

// GetDeposit returns the Deposit field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetDeposit() bool {
	if o == nil || IsNil(o.Deposit) {
		var ret bool
		return ret
	}
	return *o.Deposit
}

// GetDepositOk returns a tuple with the Deposit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetDepositOk() (*bool, bool) {
	if o == nil || IsNil(o.Deposit) {
		return nil, false
	}
	return o.Deposit, true
}

// HasDeposit returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasDeposit() bool {
	if o != nil && !IsNil(o.Deposit) {
		return true
	}

	return false
}

// SetDeposit gets a reference to the given bool and assigns it to the Deposit field.
func (o *GetSecurityAccountsResponseDataInner) SetDeposit(v bool) {
	o.Deposit = &v
}

// GetDepositStatus returns the DepositStatus field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetDepositStatus() string {
	if o == nil || IsNil(o.DepositStatus) {
		var ret string
		return ret
	}
	return *o.DepositStatus
}

// GetDepositStatusOk returns a tuple with the DepositStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetDepositStatusOk() (*string, bool) {
	if o == nil || IsNil(o.DepositStatus) {
		return nil, false
	}
	return o.DepositStatus, true
}

// HasDepositStatus returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasDepositStatus() bool {
	if o != nil && !IsNil(o.DepositStatus) {
		return true
	}

	return false
}

// SetDepositStatus gets a reference to the given string and assigns it to the DepositStatus field.
func (o *GetSecurityAccountsResponseDataInner) SetDepositStatus(v string) {
	o.DepositStatus = &v
}

// GetGiftStockStatus returns the GiftStockStatus field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetGiftStockStatus() int32 {
	if o == nil || IsNil(o.GiftStockStatus) {
		var ret int32
		return ret
	}
	return *o.GiftStockStatus
}

// GetGiftStockStatusOk returns a tuple with the GiftStockStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetGiftStockStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.GiftStockStatus) {
		return nil, false
	}
	return o.GiftStockStatus, true
}

// HasGiftStockStatus returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasGiftStockStatus() bool {
	if o != nil && !IsNil(o.GiftStockStatus) {
		return true
	}

	return false
}

// SetGiftStockStatus gets a reference to the given int32 and assigns it to the GiftStockStatus field.
func (o *GetSecurityAccountsResponseDataInner) SetGiftStockStatus(v int32) {
	o.GiftStockStatus = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *GetSecurityAccountsResponseDataInner) SetIsDefault(v bool) {
	o.IsDefault = &v
}

// GetIsDefaultChecked returns the IsDefaultChecked field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetIsDefaultChecked() bool {
	if o == nil || IsNil(o.IsDefaultChecked) {
		var ret bool
		return ret
	}
	return *o.IsDefaultChecked
}

// GetIsDefaultCheckedOk returns a tuple with the IsDefaultChecked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetIsDefaultCheckedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefaultChecked) {
		return nil, false
	}
	return o.IsDefaultChecked, true
}

// HasIsDefaultChecked returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasIsDefaultChecked() bool {
	if o != nil && !IsNil(o.IsDefaultChecked) {
		return true
	}

	return false
}

// SetIsDefaultChecked gets a reference to the given bool and assigns it to the IsDefaultChecked field.
func (o *GetSecurityAccountsResponseDataInner) SetIsDefaultChecked(v bool) {
	o.IsDefaultChecked = &v
}

// GetOpenAccountUrl returns the OpenAccountUrl field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetOpenAccountUrl() string {
	if o == nil || IsNil(o.OpenAccountUrl) {
		var ret string
		return ret
	}
	return *o.OpenAccountUrl
}

// GetOpenAccountUrlOk returns a tuple with the OpenAccountUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetOpenAccountUrlOk() (*string, bool) {
	if o == nil || IsNil(o.OpenAccountUrl) {
		return nil, false
	}
	return o.OpenAccountUrl, true
}

// HasOpenAccountUrl returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasOpenAccountUrl() bool {
	if o != nil && !IsNil(o.OpenAccountUrl) {
		return true
	}

	return false
}

// SetOpenAccountUrl gets a reference to the given string and assigns it to the OpenAccountUrl field.
func (o *GetSecurityAccountsResponseDataInner) SetOpenAccountUrl(v string) {
	o.OpenAccountUrl = &v
}

// GetOptionOpenStatus returns the OptionOpenStatus field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetOptionOpenStatus() string {
	if o == nil || IsNil(o.OptionOpenStatus) {
		var ret string
		return ret
	}
	return *o.OptionOpenStatus
}

// GetOptionOpenStatusOk returns a tuple with the OptionOpenStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetOptionOpenStatusOk() (*string, bool) {
	if o == nil || IsNil(o.OptionOpenStatus) {
		return nil, false
	}
	return o.OptionOpenStatus, true
}

// HasOptionOpenStatus returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasOptionOpenStatus() bool {
	if o != nil && !IsNil(o.OptionOpenStatus) {
		return true
	}

	return false
}

// SetOptionOpenStatus gets a reference to the given string and assigns it to the OptionOpenStatus field.
func (o *GetSecurityAccountsResponseDataInner) SetOptionOpenStatus(v string) {
	o.OptionOpenStatus = &v
}

// GetRegisterRegionId returns the RegisterRegionId field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetRegisterRegionId() int32 {
	if o == nil || IsNil(o.RegisterRegionId) {
		var ret int32
		return ret
	}
	return *o.RegisterRegionId
}

// GetRegisterRegionIdOk returns a tuple with the RegisterRegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetRegisterRegionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RegisterRegionId) {
		return nil, false
	}
	return o.RegisterRegionId, true
}

// HasRegisterRegionId returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasRegisterRegionId() bool {
	if o != nil && !IsNil(o.RegisterRegionId) {
		return true
	}

	return false
}

// SetRegisterRegionId gets a reference to the given int32 and assigns it to the RegisterRegionId field.
func (o *GetSecurityAccountsResponseDataInner) SetRegisterRegionId(v int32) {
	o.RegisterRegionId = &v
}

// GetRegisterTradeUrl returns the RegisterTradeUrl field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetRegisterTradeUrl() string {
	if o == nil || IsNil(o.RegisterTradeUrl) {
		var ret string
		return ret
	}
	return *o.RegisterTradeUrl
}

// GetRegisterTradeUrlOk returns a tuple with the RegisterTradeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetRegisterTradeUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RegisterTradeUrl) {
		return nil, false
	}
	return o.RegisterTradeUrl, true
}

// HasRegisterTradeUrl returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasRegisterTradeUrl() bool {
	if o != nil && !IsNil(o.RegisterTradeUrl) {
		return true
	}

	return false
}

// SetRegisterTradeUrl gets a reference to the given string and assigns it to the RegisterTradeUrl field.
func (o *GetSecurityAccountsResponseDataInner) SetRegisterTradeUrl(v string) {
	o.RegisterTradeUrl = &v
}

// GetSecAccountId returns the SecAccountId field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetSecAccountId() int32 {
	if o == nil || IsNil(o.SecAccountId) {
		var ret int32
		return ret
	}
	return *o.SecAccountId
}

// GetSecAccountIdOk returns a tuple with the SecAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetSecAccountIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SecAccountId) {
		return nil, false
	}
	return o.SecAccountId, true
}

// HasSecAccountId returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasSecAccountId() bool {
	if o != nil && !IsNil(o.SecAccountId) {
		return true
	}

	return false
}

// SetSecAccountId gets a reference to the given int32 and assigns it to the SecAccountId field.
func (o *GetSecurityAccountsResponseDataInner) SetSecAccountId(v int32) {
	o.SecAccountId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetSecurityAccountsResponseDataInner) SetStatus(v string) {
	o.Status = &v
}

// GetSupportClickIPO returns the SupportClickIPO field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetSupportClickIPO() bool {
	if o == nil || IsNil(o.SupportClickIPO) {
		var ret bool
		return ret
	}
	return *o.SupportClickIPO
}

// GetSupportClickIPOOk returns a tuple with the SupportClickIPO field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetSupportClickIPOOk() (*bool, bool) {
	if o == nil || IsNil(o.SupportClickIPO) {
		return nil, false
	}
	return o.SupportClickIPO, true
}

// HasSupportClickIPO returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasSupportClickIPO() bool {
	if o != nil && !IsNil(o.SupportClickIPO) {
		return true
	}

	return false
}

// SetSupportClickIPO gets a reference to the given bool and assigns it to the SupportClickIPO field.
func (o *GetSecurityAccountsResponseDataInner) SetSupportClickIPO(v bool) {
	o.SupportClickIPO = &v
}

// GetSupportOpenOption returns the SupportOpenOption field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetSupportOpenOption() bool {
	if o == nil || IsNil(o.SupportOpenOption) {
		var ret bool
		return ret
	}
	return *o.SupportOpenOption
}

// GetSupportOpenOptionOk returns a tuple with the SupportOpenOption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetSupportOpenOptionOk() (*bool, bool) {
	if o == nil || IsNil(o.SupportOpenOption) {
		return nil, false
	}
	return o.SupportOpenOption, true
}

// HasSupportOpenOption returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasSupportOpenOption() bool {
	if o != nil && !IsNil(o.SupportOpenOption) {
		return true
	}

	return false
}

// SetSupportOpenOption gets a reference to the given bool and assigns it to the SupportOpenOption field.
func (o *GetSecurityAccountsResponseDataInner) SetSupportOpenOption(v bool) {
	o.SupportOpenOption = &v
}

// GetSupportOutsideRth returns the SupportOutsideRth field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetSupportOutsideRth() bool {
	if o == nil || IsNil(o.SupportOutsideRth) {
		var ret bool
		return ret
	}
	return *o.SupportOutsideRth
}

// GetSupportOutsideRthOk returns a tuple with the SupportOutsideRth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetSupportOutsideRthOk() (*bool, bool) {
	if o == nil || IsNil(o.SupportOutsideRth) {
		return nil, false
	}
	return o.SupportOutsideRth, true
}

// HasSupportOutsideRth returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasSupportOutsideRth() bool {
	if o != nil && !IsNil(o.SupportOutsideRth) {
		return true
	}

	return false
}

// SetSupportOutsideRth gets a reference to the given bool and assigns it to the SupportOutsideRth field.
func (o *GetSecurityAccountsResponseDataInner) SetSupportOutsideRth(v bool) {
	o.SupportOutsideRth = &v
}

// GetTickerTypes returns the TickerTypes field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetTickerTypes() []GetSecurityAccountsResponseDataInnerTickerTypesInner {
	if o == nil || IsNil(o.TickerTypes) {
		var ret []GetSecurityAccountsResponseDataInnerTickerTypesInner
		return ret
	}
	return o.TickerTypes
}

// GetTickerTypesOk returns a tuple with the TickerTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetTickerTypesOk() ([]GetSecurityAccountsResponseDataInnerTickerTypesInner, bool) {
	if o == nil || IsNil(o.TickerTypes) {
		return nil, false
	}
	return o.TickerTypes, true
}

// HasTickerTypes returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasTickerTypes() bool {
	if o != nil && !IsNil(o.TickerTypes) {
		return true
	}

	return false
}

// SetTickerTypes gets a reference to the given []GetSecurityAccountsResponseDataInnerTickerTypesInner and assigns it to the TickerTypes field.
func (o *GetSecurityAccountsResponseDataInner) SetTickerTypes(v []GetSecurityAccountsResponseDataInnerTickerTypesInner) {
	o.TickerTypes = v
}

// GetTimeInForces returns the TimeInForces field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetTimeInForces() []GetSecurityAccountsResponseDataInnerTimeInForcesInner {
	if o == nil || IsNil(o.TimeInForces) {
		var ret []GetSecurityAccountsResponseDataInnerTimeInForcesInner
		return ret
	}
	return o.TimeInForces
}

// GetTimeInForcesOk returns a tuple with the TimeInForces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetTimeInForcesOk() ([]GetSecurityAccountsResponseDataInnerTimeInForcesInner, bool) {
	if o == nil || IsNil(o.TimeInForces) {
		return nil, false
	}
	return o.TimeInForces, true
}

// HasTimeInForces returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasTimeInForces() bool {
	if o != nil && !IsNil(o.TimeInForces) {
		return true
	}

	return false
}

// SetTimeInForces gets a reference to the given []GetSecurityAccountsResponseDataInnerTimeInForcesInner and assigns it to the TimeInForces field.
func (o *GetSecurityAccountsResponseDataInner) SetTimeInForces(v []GetSecurityAccountsResponseDataInnerTimeInForcesInner) {
	o.TimeInForces = v
}

// GetUserTradePermissionVOs returns the UserTradePermissionVOs field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseDataInner) GetUserTradePermissionVOs() []GetSecurityAccountsResponseDataInnerUserTradePermissionVOsInner {
	if o == nil || IsNil(o.UserTradePermissionVOs) {
		var ret []GetSecurityAccountsResponseDataInnerUserTradePermissionVOsInner
		return ret
	}
	return o.UserTradePermissionVOs
}

// GetUserTradePermissionVOsOk returns a tuple with the UserTradePermissionVOs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseDataInner) GetUserTradePermissionVOsOk() ([]GetSecurityAccountsResponseDataInnerUserTradePermissionVOsInner, bool) {
	if o == nil || IsNil(o.UserTradePermissionVOs) {
		return nil, false
	}
	return o.UserTradePermissionVOs, true
}

// HasUserTradePermissionVOs returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseDataInner) HasUserTradePermissionVOs() bool {
	if o != nil && !IsNil(o.UserTradePermissionVOs) {
		return true
	}

	return false
}

// SetUserTradePermissionVOs gets a reference to the given []GetSecurityAccountsResponseDataInnerUserTradePermissionVOsInner and assigns it to the UserTradePermissionVOs field.
func (o *GetSecurityAccountsResponseDataInner) SetUserTradePermissionVOs(v []GetSecurityAccountsResponseDataInnerUserTradePermissionVOsInner) {
	o.UserTradePermissionVOs = v
}

func (o GetSecurityAccountsResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSecurityAccountsResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountTypes) {
		toSerialize["accountTypes"] = o.AccountTypes
	}
	if !IsNil(o.AllowDeposit) {
		toSerialize["allowDeposit"] = o.AllowDeposit
	}
	if !IsNil(o.BrokerAccountId) {
		toSerialize["brokerAccountId"] = o.BrokerAccountId
	}
	if !IsNil(o.BrokerId) {
		toSerialize["brokerId"] = o.BrokerId
	}
	if !IsNil(o.BrokerName) {
		toSerialize["brokerName"] = o.BrokerName
	}
	if !IsNil(o.ComboTypes) {
		toSerialize["comboTypes"] = o.ComboTypes
	}
	if !IsNil(o.CustomerType) {
		toSerialize["customerType"] = o.CustomerType
	}
	if !IsNil(o.Deposit) {
		toSerialize["deposit"] = o.Deposit
	}
	if !IsNil(o.DepositStatus) {
		toSerialize["depositStatus"] = o.DepositStatus
	}
	if !IsNil(o.GiftStockStatus) {
		toSerialize["giftStockStatus"] = o.GiftStockStatus
	}
	if !IsNil(o.IsDefault) {
		toSerialize["isDefault"] = o.IsDefault
	}
	if !IsNil(o.IsDefaultChecked) {
		toSerialize["isDefaultChecked"] = o.IsDefaultChecked
	}
	if !IsNil(o.OpenAccountUrl) {
		toSerialize["openAccountUrl"] = o.OpenAccountUrl
	}
	if !IsNil(o.OptionOpenStatus) {
		toSerialize["optionOpenStatus"] = o.OptionOpenStatus
	}
	if !IsNil(o.RegisterRegionId) {
		toSerialize["registerRegionId"] = o.RegisterRegionId
	}
	if !IsNil(o.RegisterTradeUrl) {
		toSerialize["registerTradeUrl"] = o.RegisterTradeUrl
	}
	if !IsNil(o.SecAccountId) {
		toSerialize["secAccountId"] = o.SecAccountId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.SupportClickIPO) {
		toSerialize["supportClickIPO"] = o.SupportClickIPO
	}
	if !IsNil(o.SupportOpenOption) {
		toSerialize["supportOpenOption"] = o.SupportOpenOption
	}
	if !IsNil(o.SupportOutsideRth) {
		toSerialize["supportOutsideRth"] = o.SupportOutsideRth
	}
	if !IsNil(o.TickerTypes) {
		toSerialize["tickerTypes"] = o.TickerTypes
	}
	if !IsNil(o.TimeInForces) {
		toSerialize["timeInForces"] = o.TimeInForces
	}
	if !IsNil(o.UserTradePermissionVOs) {
		toSerialize["userTradePermissionVOs"] = o.UserTradePermissionVOs
	}
	return toSerialize, nil
}

type NullableGetSecurityAccountsResponseDataInner struct {
	value *GetSecurityAccountsResponseDataInner
	isSet bool
}

func (v NullableGetSecurityAccountsResponseDataInner) Get() *GetSecurityAccountsResponseDataInner {
	return v.value
}

func (v *NullableGetSecurityAccountsResponseDataInner) Set(val *GetSecurityAccountsResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSecurityAccountsResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSecurityAccountsResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSecurityAccountsResponseDataInner(val *GetSecurityAccountsResponseDataInner) *NullableGetSecurityAccountsResponseDataInner {
	return &NullableGetSecurityAccountsResponseDataInner{value: val, isSet: true}
}

func (v NullableGetSecurityAccountsResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSecurityAccountsResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


