/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OrderSide the model 'OrderSide'
type OrderSide string

// List of OrderSide
const (
	BUY OrderSide = "BUY"
	SELL OrderSide = "SELL"
)
