/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetOrdersItemOrdersInnerTicker type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrdersItemOrdersInnerTicker{}

// GetOrdersItemOrdersInnerTicker struct for GetOrdersItemOrdersInnerTicker
type GetOrdersItemOrdersInnerTicker struct {
	CurrencyCode *string `json:"currencyCode,omitempty"`
	CurrencyId *int32 `json:"currencyId,omitempty"`
	DisExchangeCode *string `json:"disExchangeCode,omitempty"`
	DisSymbol *string `json:"disSymbol,omitempty"`
	ExchangeCode *string `json:"exchangeCode,omitempty"`
	ExchangeId *int32 `json:"exchangeId,omitempty"`
	ExchangeTrade *bool `json:"exchangeTrade,omitempty"`
	ExtType []map[string]interface{} `json:"extType,omitempty"`
	ListStatus *int32 `json:"listStatus,omitempty"`
	Name *string `json:"name,omitempty"`
	RegionId *int32 `json:"regionId,omitempty"`
	RegionIsoCode *string `json:"regionIsoCode,omitempty"`
	RegionName *string `json:"regionName,omitempty"`
	SecType []int32 `json:"secType,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
	TickerId *int32 `json:"tickerId,omitempty"`
	TinyName *string `json:"tinyName,omitempty"`
	Type *int32 `json:"type,omitempty"`
}

// NewGetOrdersItemOrdersInnerTicker instantiates a new GetOrdersItemOrdersInnerTicker object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrdersItemOrdersInnerTicker() *GetOrdersItemOrdersInnerTicker {
	this := GetOrdersItemOrdersInnerTicker{}
	return &this
}

// NewGetOrdersItemOrdersInnerTickerWithDefaults instantiates a new GetOrdersItemOrdersInnerTicker object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrdersItemOrdersInnerTickerWithDefaults() *GetOrdersItemOrdersInnerTicker {
	this := GetOrdersItemOrdersInnerTicker{}
	return &this
}

// GetCurrencyCode returns the CurrencyCode field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetCurrencyCode() string {
	if o == nil || IsNil(o.CurrencyCode) {
		var ret string
		return ret
	}
	return *o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyCode) {
		return nil, false
	}
	return o.CurrencyCode, true
}

// HasCurrencyCode returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasCurrencyCode() bool {
	if o != nil && !IsNil(o.CurrencyCode) {
		return true
	}

	return false
}

// SetCurrencyCode gets a reference to the given string and assigns it to the CurrencyCode field.
func (o *GetOrdersItemOrdersInnerTicker) SetCurrencyCode(v string) {
	o.CurrencyCode = &v
}

// GetCurrencyId returns the CurrencyId field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetCurrencyId() int32 {
	if o == nil || IsNil(o.CurrencyId) {
		var ret int32
		return ret
	}
	return *o.CurrencyId
}

// GetCurrencyIdOk returns a tuple with the CurrencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetCurrencyIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrencyId) {
		return nil, false
	}
	return o.CurrencyId, true
}

// HasCurrencyId returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasCurrencyId() bool {
	if o != nil && !IsNil(o.CurrencyId) {
		return true
	}

	return false
}

// SetCurrencyId gets a reference to the given int32 and assigns it to the CurrencyId field.
func (o *GetOrdersItemOrdersInnerTicker) SetCurrencyId(v int32) {
	o.CurrencyId = &v
}

// GetDisExchangeCode returns the DisExchangeCode field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetDisExchangeCode() string {
	if o == nil || IsNil(o.DisExchangeCode) {
		var ret string
		return ret
	}
	return *o.DisExchangeCode
}

// GetDisExchangeCodeOk returns a tuple with the DisExchangeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetDisExchangeCodeOk() (*string, bool) {
	if o == nil || IsNil(o.DisExchangeCode) {
		return nil, false
	}
	return o.DisExchangeCode, true
}

// HasDisExchangeCode returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasDisExchangeCode() bool {
	if o != nil && !IsNil(o.DisExchangeCode) {
		return true
	}

	return false
}

// SetDisExchangeCode gets a reference to the given string and assigns it to the DisExchangeCode field.
func (o *GetOrdersItemOrdersInnerTicker) SetDisExchangeCode(v string) {
	o.DisExchangeCode = &v
}

// GetDisSymbol returns the DisSymbol field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetDisSymbol() string {
	if o == nil || IsNil(o.DisSymbol) {
		var ret string
		return ret
	}
	return *o.DisSymbol
}

// GetDisSymbolOk returns a tuple with the DisSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetDisSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.DisSymbol) {
		return nil, false
	}
	return o.DisSymbol, true
}

// HasDisSymbol returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasDisSymbol() bool {
	if o != nil && !IsNil(o.DisSymbol) {
		return true
	}

	return false
}

// SetDisSymbol gets a reference to the given string and assigns it to the DisSymbol field.
func (o *GetOrdersItemOrdersInnerTicker) SetDisSymbol(v string) {
	o.DisSymbol = &v
}

// GetExchangeCode returns the ExchangeCode field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetExchangeCode() string {
	if o == nil || IsNil(o.ExchangeCode) {
		var ret string
		return ret
	}
	return *o.ExchangeCode
}

// GetExchangeCodeOk returns a tuple with the ExchangeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetExchangeCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ExchangeCode) {
		return nil, false
	}
	return o.ExchangeCode, true
}

// HasExchangeCode returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasExchangeCode() bool {
	if o != nil && !IsNil(o.ExchangeCode) {
		return true
	}

	return false
}

// SetExchangeCode gets a reference to the given string and assigns it to the ExchangeCode field.
func (o *GetOrdersItemOrdersInnerTicker) SetExchangeCode(v string) {
	o.ExchangeCode = &v
}

// GetExchangeId returns the ExchangeId field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetExchangeId() int32 {
	if o == nil || IsNil(o.ExchangeId) {
		var ret int32
		return ret
	}
	return *o.ExchangeId
}

// GetExchangeIdOk returns a tuple with the ExchangeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetExchangeIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ExchangeId) {
		return nil, false
	}
	return o.ExchangeId, true
}

// HasExchangeId returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasExchangeId() bool {
	if o != nil && !IsNil(o.ExchangeId) {
		return true
	}

	return false
}

// SetExchangeId gets a reference to the given int32 and assigns it to the ExchangeId field.
func (o *GetOrdersItemOrdersInnerTicker) SetExchangeId(v int32) {
	o.ExchangeId = &v
}

// GetExchangeTrade returns the ExchangeTrade field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetExchangeTrade() bool {
	if o == nil || IsNil(o.ExchangeTrade) {
		var ret bool
		return ret
	}
	return *o.ExchangeTrade
}

// GetExchangeTradeOk returns a tuple with the ExchangeTrade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetExchangeTradeOk() (*bool, bool) {
	if o == nil || IsNil(o.ExchangeTrade) {
		return nil, false
	}
	return o.ExchangeTrade, true
}

// HasExchangeTrade returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasExchangeTrade() bool {
	if o != nil && !IsNil(o.ExchangeTrade) {
		return true
	}

	return false
}

// SetExchangeTrade gets a reference to the given bool and assigns it to the ExchangeTrade field.
func (o *GetOrdersItemOrdersInnerTicker) SetExchangeTrade(v bool) {
	o.ExchangeTrade = &v
}

// GetExtType returns the ExtType field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetExtType() []map[string]interface{} {
	if o == nil || IsNil(o.ExtType) {
		var ret []map[string]interface{}
		return ret
	}
	return o.ExtType
}

// GetExtTypeOk returns a tuple with the ExtType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetExtTypeOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExtType) {
		return nil, false
	}
	return o.ExtType, true
}

// HasExtType returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasExtType() bool {
	if o != nil && !IsNil(o.ExtType) {
		return true
	}

	return false
}

// SetExtType gets a reference to the given []map[string]interface{} and assigns it to the ExtType field.
func (o *GetOrdersItemOrdersInnerTicker) SetExtType(v []map[string]interface{}) {
	o.ExtType = v
}

// GetListStatus returns the ListStatus field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetListStatus() int32 {
	if o == nil || IsNil(o.ListStatus) {
		var ret int32
		return ret
	}
	return *o.ListStatus
}

// GetListStatusOk returns a tuple with the ListStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetListStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.ListStatus) {
		return nil, false
	}
	return o.ListStatus, true
}

// HasListStatus returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasListStatus() bool {
	if o != nil && !IsNil(o.ListStatus) {
		return true
	}

	return false
}

// SetListStatus gets a reference to the given int32 and assigns it to the ListStatus field.
func (o *GetOrdersItemOrdersInnerTicker) SetListStatus(v int32) {
	o.ListStatus = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetOrdersItemOrdersInnerTicker) SetName(v string) {
	o.Name = &v
}

// GetRegionId returns the RegionId field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetRegionId() int32 {
	if o == nil || IsNil(o.RegionId) {
		var ret int32
		return ret
	}
	return *o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetRegionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RegionId) {
		return nil, false
	}
	return o.RegionId, true
}

// HasRegionId returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasRegionId() bool {
	if o != nil && !IsNil(o.RegionId) {
		return true
	}

	return false
}

// SetRegionId gets a reference to the given int32 and assigns it to the RegionId field.
func (o *GetOrdersItemOrdersInnerTicker) SetRegionId(v int32) {
	o.RegionId = &v
}

// GetRegionIsoCode returns the RegionIsoCode field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetRegionIsoCode() string {
	if o == nil || IsNil(o.RegionIsoCode) {
		var ret string
		return ret
	}
	return *o.RegionIsoCode
}

// GetRegionIsoCodeOk returns a tuple with the RegionIsoCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetRegionIsoCodeOk() (*string, bool) {
	if o == nil || IsNil(o.RegionIsoCode) {
		return nil, false
	}
	return o.RegionIsoCode, true
}

// HasRegionIsoCode returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasRegionIsoCode() bool {
	if o != nil && !IsNil(o.RegionIsoCode) {
		return true
	}

	return false
}

// SetRegionIsoCode gets a reference to the given string and assigns it to the RegionIsoCode field.
func (o *GetOrdersItemOrdersInnerTicker) SetRegionIsoCode(v string) {
	o.RegionIsoCode = &v
}

// GetRegionName returns the RegionName field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetRegionName() string {
	if o == nil || IsNil(o.RegionName) {
		var ret string
		return ret
	}
	return *o.RegionName
}

// GetRegionNameOk returns a tuple with the RegionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetRegionNameOk() (*string, bool) {
	if o == nil || IsNil(o.RegionName) {
		return nil, false
	}
	return o.RegionName, true
}

// HasRegionName returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasRegionName() bool {
	if o != nil && !IsNil(o.RegionName) {
		return true
	}

	return false
}

// SetRegionName gets a reference to the given string and assigns it to the RegionName field.
func (o *GetOrdersItemOrdersInnerTicker) SetRegionName(v string) {
	o.RegionName = &v
}

// GetSecType returns the SecType field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetSecType() []int32 {
	if o == nil || IsNil(o.SecType) {
		var ret []int32
		return ret
	}
	return o.SecType
}

// GetSecTypeOk returns a tuple with the SecType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetSecTypeOk() ([]int32, bool) {
	if o == nil || IsNil(o.SecType) {
		return nil, false
	}
	return o.SecType, true
}

// HasSecType returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasSecType() bool {
	if o != nil && !IsNil(o.SecType) {
		return true
	}

	return false
}

// SetSecType gets a reference to the given []int32 and assigns it to the SecType field.
func (o *GetOrdersItemOrdersInnerTicker) SetSecType(v []int32) {
	o.SecType = v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *GetOrdersItemOrdersInnerTicker) SetSymbol(v string) {
	o.Symbol = &v
}

// GetTickerId returns the TickerId field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetTickerId() int32 {
	if o == nil || IsNil(o.TickerId) {
		var ret int32
		return ret
	}
	return *o.TickerId
}

// GetTickerIdOk returns a tuple with the TickerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetTickerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TickerId) {
		return nil, false
	}
	return o.TickerId, true
}

// HasTickerId returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasTickerId() bool {
	if o != nil && !IsNil(o.TickerId) {
		return true
	}

	return false
}

// SetTickerId gets a reference to the given int32 and assigns it to the TickerId field.
func (o *GetOrdersItemOrdersInnerTicker) SetTickerId(v int32) {
	o.TickerId = &v
}

// GetTinyName returns the TinyName field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetTinyName() string {
	if o == nil || IsNil(o.TinyName) {
		var ret string
		return ret
	}
	return *o.TinyName
}

// GetTinyNameOk returns a tuple with the TinyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetTinyNameOk() (*string, bool) {
	if o == nil || IsNil(o.TinyName) {
		return nil, false
	}
	return o.TinyName, true
}

// HasTinyName returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasTinyName() bool {
	if o != nil && !IsNil(o.TinyName) {
		return true
	}

	return false
}

// SetTinyName gets a reference to the given string and assigns it to the TinyName field.
func (o *GetOrdersItemOrdersInnerTicker) SetTinyName(v string) {
	o.TinyName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetOrdersItemOrdersInnerTicker) GetType() int32 {
	if o == nil || IsNil(o.Type) {
		var ret int32
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrdersInnerTicker) GetTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetOrdersItemOrdersInnerTicker) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given int32 and assigns it to the Type field.
func (o *GetOrdersItemOrdersInnerTicker) SetType(v int32) {
	o.Type = &v
}

func (o GetOrdersItemOrdersInnerTicker) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrdersItemOrdersInnerTicker) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrencyCode) {
		toSerialize["currencyCode"] = o.CurrencyCode
	}
	if !IsNil(o.CurrencyId) {
		toSerialize["currencyId"] = o.CurrencyId
	}
	if !IsNil(o.DisExchangeCode) {
		toSerialize["disExchangeCode"] = o.DisExchangeCode
	}
	if !IsNil(o.DisSymbol) {
		toSerialize["disSymbol"] = o.DisSymbol
	}
	if !IsNil(o.ExchangeCode) {
		toSerialize["exchangeCode"] = o.ExchangeCode
	}
	if !IsNil(o.ExchangeId) {
		toSerialize["exchangeId"] = o.ExchangeId
	}
	if !IsNil(o.ExchangeTrade) {
		toSerialize["exchangeTrade"] = o.ExchangeTrade
	}
	if !IsNil(o.ExtType) {
		toSerialize["extType"] = o.ExtType
	}
	if !IsNil(o.ListStatus) {
		toSerialize["listStatus"] = o.ListStatus
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RegionId) {
		toSerialize["regionId"] = o.RegionId
	}
	if !IsNil(o.RegionIsoCode) {
		toSerialize["regionIsoCode"] = o.RegionIsoCode
	}
	if !IsNil(o.RegionName) {
		toSerialize["regionName"] = o.RegionName
	}
	if !IsNil(o.SecType) {
		toSerialize["secType"] = o.SecType
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.TickerId) {
		toSerialize["tickerId"] = o.TickerId
	}
	if !IsNil(o.TinyName) {
		toSerialize["tinyName"] = o.TinyName
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableGetOrdersItemOrdersInnerTicker struct {
	value *GetOrdersItemOrdersInnerTicker
	isSet bool
}

func (v NullableGetOrdersItemOrdersInnerTicker) Get() *GetOrdersItemOrdersInnerTicker {
	return v.value
}

func (v *NullableGetOrdersItemOrdersInnerTicker) Set(val *GetOrdersItemOrdersInnerTicker) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrdersItemOrdersInnerTicker) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrdersItemOrdersInnerTicker) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrdersItemOrdersInnerTicker(val *GetOrdersItemOrdersInnerTicker) *NullableGetOrdersItemOrdersInnerTicker {
	return &NullableGetOrdersItemOrdersInnerTicker{value: val, isSet: true}
}

func (v NullableGetOrdersItemOrdersInnerTicker) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrdersItemOrdersInnerTicker) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


