/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostTradeTokenResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTradeTokenResponseData{}

// PostTradeTokenResponseData struct for PostTradeTokenResponseData
type PostTradeTokenResponseData struct {
	TradeToken *string `json:"tradeToken,omitempty"`
	TradeTokenExpireIn *int32 `json:"tradeTokenExpireIn,omitempty"`
}

// NewPostTradeTokenResponseData instantiates a new PostTradeTokenResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTradeTokenResponseData() *PostTradeTokenResponseData {
	this := PostTradeTokenResponseData{}
	return &this
}

// NewPostTradeTokenResponseDataWithDefaults instantiates a new PostTradeTokenResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTradeTokenResponseDataWithDefaults() *PostTradeTokenResponseData {
	this := PostTradeTokenResponseData{}
	return &this
}

// GetTradeToken returns the TradeToken field value if set, zero value otherwise.
func (o *PostTradeTokenResponseData) GetTradeToken() string {
	if o == nil || IsNil(o.TradeToken) {
		var ret string
		return ret
	}
	return *o.TradeToken
}

// GetTradeTokenOk returns a tuple with the TradeToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTradeTokenResponseData) GetTradeTokenOk() (*string, bool) {
	if o == nil || IsNil(o.TradeToken) {
		return nil, false
	}
	return o.TradeToken, true
}

// HasTradeToken returns a boolean if a field has been set.
func (o *PostTradeTokenResponseData) HasTradeToken() bool {
	if o != nil && !IsNil(o.TradeToken) {
		return true
	}

	return false
}

// SetTradeToken gets a reference to the given string and assigns it to the TradeToken field.
func (o *PostTradeTokenResponseData) SetTradeToken(v string) {
	o.TradeToken = &v
}

// GetTradeTokenExpireIn returns the TradeTokenExpireIn field value if set, zero value otherwise.
func (o *PostTradeTokenResponseData) GetTradeTokenExpireIn() int32 {
	if o == nil || IsNil(o.TradeTokenExpireIn) {
		var ret int32
		return ret
	}
	return *o.TradeTokenExpireIn
}

// GetTradeTokenExpireInOk returns a tuple with the TradeTokenExpireIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTradeTokenResponseData) GetTradeTokenExpireInOk() (*int32, bool) {
	if o == nil || IsNil(o.TradeTokenExpireIn) {
		return nil, false
	}
	return o.TradeTokenExpireIn, true
}

// HasTradeTokenExpireIn returns a boolean if a field has been set.
func (o *PostTradeTokenResponseData) HasTradeTokenExpireIn() bool {
	if o != nil && !IsNil(o.TradeTokenExpireIn) {
		return true
	}

	return false
}

// SetTradeTokenExpireIn gets a reference to the given int32 and assigns it to the TradeTokenExpireIn field.
func (o *PostTradeTokenResponseData) SetTradeTokenExpireIn(v int32) {
	o.TradeTokenExpireIn = &v
}

func (o PostTradeTokenResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTradeTokenResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TradeToken) {
		toSerialize["tradeToken"] = o.TradeToken
	}
	if !IsNil(o.TradeTokenExpireIn) {
		toSerialize["tradeTokenExpireIn"] = o.TradeTokenExpireIn
	}
	return toSerialize, nil
}

type NullablePostTradeTokenResponseData struct {
	value *PostTradeTokenResponseData
	isSet bool
}

func (v NullablePostTradeTokenResponseData) Get() *PostTradeTokenResponseData {
	return v.value
}

func (v *NullablePostTradeTokenResponseData) Set(val *PostTradeTokenResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTradeTokenResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTradeTokenResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTradeTokenResponseData(val *PostTradeTokenResponseData) *NullablePostTradeTokenResponseData {
	return &NullablePostTradeTokenResponseData{value: val, isSet: true}
}

func (v NullablePostTradeTokenResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTradeTokenResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


