/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetTransfersRequest struct for GetTransfersRequest
type GetTransfersRequest struct {
	PageSize float32 `json:"pageSize,omitempty"`
	LastRecordId string `json:"lastRecordId,omitempty"`
}
