/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AccountType number: 1, email: 2
type AccountType int32

// List of AccountType
const (
	_1 AccountType = 1
	_2 AccountType = 2
)
