/*
Webull API

Webull API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetStockQuoteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStockQuoteResponse{}

// GetStockQuoteResponse struct for GetStockQuoteResponse
type GetStockQuoteResponse struct {
	AvgVol10D *string `json:"avgVol10D,omitempty"`
	AvgVol3M *string `json:"avgVol3M,omitempty"`
	Beta3Y *string `json:"beta3Y,omitempty"`
	Bps *string `json:"bps,omitempty"`
	Change *string `json:"change,omitempty"`
	ChangeRatio *string `json:"changeRatio,omitempty"`
	Close *string `json:"close,omitempty"`
	CurrencyCode *string `json:"currencyCode,omitempty"`
	DerivativeSupport *int32 `json:"derivativeSupport,omitempty"`
	Dividend *string `json:"dividend,omitempty"`
	Eps *string `json:"eps,omitempty"`
	EpsTtm *string `json:"epsTtm,omitempty"`
	FiftyTwoWkHigh *string `json:"fiftyTwoWkHigh,omitempty"`
	FiftyTwoWkLow *string `json:"fiftyTwoWkLow,omitempty"`
	High *string `json:"high,omitempty"`
	InceptionDate *string `json:"inceptionDate,omitempty"`
	LatestDividendDate *string `json:"latestDividendDate,omitempty"`
	LimitDown *string `json:"limitDown,omitempty"`
	LimitUp *string `json:"limitUp,omitempty"`
	LotSize *string `json:"lotSize,omitempty"`
	Low *string `json:"low,omitempty"`
	NetAsset *string `json:"netAsset,omitempty"`
	NetExpenseRatio *string `json:"netExpenseRatio,omitempty"`
	NetValue *string `json:"netValue,omitempty"`
	NtvSize *int32 `json:"ntvSize,omitempty"`
	Open *string `json:"open,omitempty"`
	PChRatio *string `json:"pChRatio,omitempty"`
	PChange *string `json:"pChange,omitempty"`
	PPrice *string `json:"pPrice,omitempty"`
	Pe *string `json:"pe,omitempty"`
	PeTtm *string `json:"peTtm,omitempty"`
	PreClose *string `json:"preClose,omitempty"`
	Rating *int32 `json:"rating,omitempty"`
	ReturnThisYear *string `json:"returnThisYear,omitempty"`
	Status *string `json:"status,omitempty"`
	TickerId *int32 `json:"tickerId,omitempty"`
	TimeZone *string `json:"timeZone,omitempty"`
	TotalAsset *string `json:"totalAsset,omitempty"`
	TradeTime *string `json:"tradeTime,omitempty"`
	TzName *string `json:"tzName,omitempty"`
	VibrateRatio *string `json:"vibrateRatio,omitempty"`
	Volume *string `json:"volume,omitempty"`
	Yield *string `json:"yield,omitempty"`
	Yield1Y *string `json:"yield1Y,omitempty"`
}

// NewGetStockQuoteResponse instantiates a new GetStockQuoteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStockQuoteResponse() *GetStockQuoteResponse {
	this := GetStockQuoteResponse{}
	return &this
}

// NewGetStockQuoteResponseWithDefaults instantiates a new GetStockQuoteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStockQuoteResponseWithDefaults() *GetStockQuoteResponse {
	this := GetStockQuoteResponse{}
	return &this
}

// GetAvgVol10D returns the AvgVol10D field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetAvgVol10D() string {
	if o == nil || IsNil(o.AvgVol10D) {
		var ret string
		return ret
	}
	return *o.AvgVol10D
}

// GetAvgVol10DOk returns a tuple with the AvgVol10D field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetAvgVol10DOk() (*string, bool) {
	if o == nil || IsNil(o.AvgVol10D) {
		return nil, false
	}
	return o.AvgVol10D, true
}

// HasAvgVol10D returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasAvgVol10D() bool {
	if o != nil && !IsNil(o.AvgVol10D) {
		return true
	}

	return false
}

// SetAvgVol10D gets a reference to the given string and assigns it to the AvgVol10D field.
func (o *GetStockQuoteResponse) SetAvgVol10D(v string) {
	o.AvgVol10D = &v
}

// GetAvgVol3M returns the AvgVol3M field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetAvgVol3M() string {
	if o == nil || IsNil(o.AvgVol3M) {
		var ret string
		return ret
	}
	return *o.AvgVol3M
}

// GetAvgVol3MOk returns a tuple with the AvgVol3M field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetAvgVol3MOk() (*string, bool) {
	if o == nil || IsNil(o.AvgVol3M) {
		return nil, false
	}
	return o.AvgVol3M, true
}

// HasAvgVol3M returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasAvgVol3M() bool {
	if o != nil && !IsNil(o.AvgVol3M) {
		return true
	}

	return false
}

// SetAvgVol3M gets a reference to the given string and assigns it to the AvgVol3M field.
func (o *GetStockQuoteResponse) SetAvgVol3M(v string) {
	o.AvgVol3M = &v
}

// GetBeta3Y returns the Beta3Y field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetBeta3Y() string {
	if o == nil || IsNil(o.Beta3Y) {
		var ret string
		return ret
	}
	return *o.Beta3Y
}

// GetBeta3YOk returns a tuple with the Beta3Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetBeta3YOk() (*string, bool) {
	if o == nil || IsNil(o.Beta3Y) {
		return nil, false
	}
	return o.Beta3Y, true
}

// HasBeta3Y returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasBeta3Y() bool {
	if o != nil && !IsNil(o.Beta3Y) {
		return true
	}

	return false
}

// SetBeta3Y gets a reference to the given string and assigns it to the Beta3Y field.
func (o *GetStockQuoteResponse) SetBeta3Y(v string) {
	o.Beta3Y = &v
}

// GetBps returns the Bps field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetBps() string {
	if o == nil || IsNil(o.Bps) {
		var ret string
		return ret
	}
	return *o.Bps
}

// GetBpsOk returns a tuple with the Bps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetBpsOk() (*string, bool) {
	if o == nil || IsNil(o.Bps) {
		return nil, false
	}
	return o.Bps, true
}

// HasBps returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasBps() bool {
	if o != nil && !IsNil(o.Bps) {
		return true
	}

	return false
}

// SetBps gets a reference to the given string and assigns it to the Bps field.
func (o *GetStockQuoteResponse) SetBps(v string) {
	o.Bps = &v
}

// GetChange returns the Change field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetChange() string {
	if o == nil || IsNil(o.Change) {
		var ret string
		return ret
	}
	return *o.Change
}

// GetChangeOk returns a tuple with the Change field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetChangeOk() (*string, bool) {
	if o == nil || IsNil(o.Change) {
		return nil, false
	}
	return o.Change, true
}

// HasChange returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasChange() bool {
	if o != nil && !IsNil(o.Change) {
		return true
	}

	return false
}

// SetChange gets a reference to the given string and assigns it to the Change field.
func (o *GetStockQuoteResponse) SetChange(v string) {
	o.Change = &v
}

// GetChangeRatio returns the ChangeRatio field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetChangeRatio() string {
	if o == nil || IsNil(o.ChangeRatio) {
		var ret string
		return ret
	}
	return *o.ChangeRatio
}

// GetChangeRatioOk returns a tuple with the ChangeRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetChangeRatioOk() (*string, bool) {
	if o == nil || IsNil(o.ChangeRatio) {
		return nil, false
	}
	return o.ChangeRatio, true
}

// HasChangeRatio returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasChangeRatio() bool {
	if o != nil && !IsNil(o.ChangeRatio) {
		return true
	}

	return false
}

// SetChangeRatio gets a reference to the given string and assigns it to the ChangeRatio field.
func (o *GetStockQuoteResponse) SetChangeRatio(v string) {
	o.ChangeRatio = &v
}

// GetClose returns the Close field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetClose() string {
	if o == nil || IsNil(o.Close) {
		var ret string
		return ret
	}
	return *o.Close
}

// GetCloseOk returns a tuple with the Close field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetCloseOk() (*string, bool) {
	if o == nil || IsNil(o.Close) {
		return nil, false
	}
	return o.Close, true
}

// HasClose returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasClose() bool {
	if o != nil && !IsNil(o.Close) {
		return true
	}

	return false
}

// SetClose gets a reference to the given string and assigns it to the Close field.
func (o *GetStockQuoteResponse) SetClose(v string) {
	o.Close = &v
}

// GetCurrencyCode returns the CurrencyCode field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetCurrencyCode() string {
	if o == nil || IsNil(o.CurrencyCode) {
		var ret string
		return ret
	}
	return *o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyCode) {
		return nil, false
	}
	return o.CurrencyCode, true
}

// HasCurrencyCode returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasCurrencyCode() bool {
	if o != nil && !IsNil(o.CurrencyCode) {
		return true
	}

	return false
}

// SetCurrencyCode gets a reference to the given string and assigns it to the CurrencyCode field.
func (o *GetStockQuoteResponse) SetCurrencyCode(v string) {
	o.CurrencyCode = &v
}

// GetDerivativeSupport returns the DerivativeSupport field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetDerivativeSupport() int32 {
	if o == nil || IsNil(o.DerivativeSupport) {
		var ret int32
		return ret
	}
	return *o.DerivativeSupport
}

// GetDerivativeSupportOk returns a tuple with the DerivativeSupport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetDerivativeSupportOk() (*int32, bool) {
	if o == nil || IsNil(o.DerivativeSupport) {
		return nil, false
	}
	return o.DerivativeSupport, true
}

// HasDerivativeSupport returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasDerivativeSupport() bool {
	if o != nil && !IsNil(o.DerivativeSupport) {
		return true
	}

	return false
}

// SetDerivativeSupport gets a reference to the given int32 and assigns it to the DerivativeSupport field.
func (o *GetStockQuoteResponse) SetDerivativeSupport(v int32) {
	o.DerivativeSupport = &v
}

// GetDividend returns the Dividend field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetDividend() string {
	if o == nil || IsNil(o.Dividend) {
		var ret string
		return ret
	}
	return *o.Dividend
}

// GetDividendOk returns a tuple with the Dividend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetDividendOk() (*string, bool) {
	if o == nil || IsNil(o.Dividend) {
		return nil, false
	}
	return o.Dividend, true
}

// HasDividend returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasDividend() bool {
	if o != nil && !IsNil(o.Dividend) {
		return true
	}

	return false
}

// SetDividend gets a reference to the given string and assigns it to the Dividend field.
func (o *GetStockQuoteResponse) SetDividend(v string) {
	o.Dividend = &v
}

// GetEps returns the Eps field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetEps() string {
	if o == nil || IsNil(o.Eps) {
		var ret string
		return ret
	}
	return *o.Eps
}

// GetEpsOk returns a tuple with the Eps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetEpsOk() (*string, bool) {
	if o == nil || IsNil(o.Eps) {
		return nil, false
	}
	return o.Eps, true
}

// HasEps returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasEps() bool {
	if o != nil && !IsNil(o.Eps) {
		return true
	}

	return false
}

// SetEps gets a reference to the given string and assigns it to the Eps field.
func (o *GetStockQuoteResponse) SetEps(v string) {
	o.Eps = &v
}

// GetEpsTtm returns the EpsTtm field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetEpsTtm() string {
	if o == nil || IsNil(o.EpsTtm) {
		var ret string
		return ret
	}
	return *o.EpsTtm
}

// GetEpsTtmOk returns a tuple with the EpsTtm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetEpsTtmOk() (*string, bool) {
	if o == nil || IsNil(o.EpsTtm) {
		return nil, false
	}
	return o.EpsTtm, true
}

// HasEpsTtm returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasEpsTtm() bool {
	if o != nil && !IsNil(o.EpsTtm) {
		return true
	}

	return false
}

// SetEpsTtm gets a reference to the given string and assigns it to the EpsTtm field.
func (o *GetStockQuoteResponse) SetEpsTtm(v string) {
	o.EpsTtm = &v
}

// GetFiftyTwoWkHigh returns the FiftyTwoWkHigh field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetFiftyTwoWkHigh() string {
	if o == nil || IsNil(o.FiftyTwoWkHigh) {
		var ret string
		return ret
	}
	return *o.FiftyTwoWkHigh
}

// GetFiftyTwoWkHighOk returns a tuple with the FiftyTwoWkHigh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetFiftyTwoWkHighOk() (*string, bool) {
	if o == nil || IsNil(o.FiftyTwoWkHigh) {
		return nil, false
	}
	return o.FiftyTwoWkHigh, true
}

// HasFiftyTwoWkHigh returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasFiftyTwoWkHigh() bool {
	if o != nil && !IsNil(o.FiftyTwoWkHigh) {
		return true
	}

	return false
}

// SetFiftyTwoWkHigh gets a reference to the given string and assigns it to the FiftyTwoWkHigh field.
func (o *GetStockQuoteResponse) SetFiftyTwoWkHigh(v string) {
	o.FiftyTwoWkHigh = &v
}

// GetFiftyTwoWkLow returns the FiftyTwoWkLow field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetFiftyTwoWkLow() string {
	if o == nil || IsNil(o.FiftyTwoWkLow) {
		var ret string
		return ret
	}
	return *o.FiftyTwoWkLow
}

// GetFiftyTwoWkLowOk returns a tuple with the FiftyTwoWkLow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetFiftyTwoWkLowOk() (*string, bool) {
	if o == nil || IsNil(o.FiftyTwoWkLow) {
		return nil, false
	}
	return o.FiftyTwoWkLow, true
}

// HasFiftyTwoWkLow returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasFiftyTwoWkLow() bool {
	if o != nil && !IsNil(o.FiftyTwoWkLow) {
		return true
	}

	return false
}

// SetFiftyTwoWkLow gets a reference to the given string and assigns it to the FiftyTwoWkLow field.
func (o *GetStockQuoteResponse) SetFiftyTwoWkLow(v string) {
	o.FiftyTwoWkLow = &v
}

// GetHigh returns the High field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetHigh() string {
	if o == nil || IsNil(o.High) {
		var ret string
		return ret
	}
	return *o.High
}

// GetHighOk returns a tuple with the High field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetHighOk() (*string, bool) {
	if o == nil || IsNil(o.High) {
		return nil, false
	}
	return o.High, true
}

// HasHigh returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasHigh() bool {
	if o != nil && !IsNil(o.High) {
		return true
	}

	return false
}

// SetHigh gets a reference to the given string and assigns it to the High field.
func (o *GetStockQuoteResponse) SetHigh(v string) {
	o.High = &v
}

// GetInceptionDate returns the InceptionDate field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetInceptionDate() string {
	if o == nil || IsNil(o.InceptionDate) {
		var ret string
		return ret
	}
	return *o.InceptionDate
}

// GetInceptionDateOk returns a tuple with the InceptionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetInceptionDateOk() (*string, bool) {
	if o == nil || IsNil(o.InceptionDate) {
		return nil, false
	}
	return o.InceptionDate, true
}

// HasInceptionDate returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasInceptionDate() bool {
	if o != nil && !IsNil(o.InceptionDate) {
		return true
	}

	return false
}

// SetInceptionDate gets a reference to the given string and assigns it to the InceptionDate field.
func (o *GetStockQuoteResponse) SetInceptionDate(v string) {
	o.InceptionDate = &v
}

// GetLatestDividendDate returns the LatestDividendDate field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetLatestDividendDate() string {
	if o == nil || IsNil(o.LatestDividendDate) {
		var ret string
		return ret
	}
	return *o.LatestDividendDate
}

// GetLatestDividendDateOk returns a tuple with the LatestDividendDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetLatestDividendDateOk() (*string, bool) {
	if o == nil || IsNil(o.LatestDividendDate) {
		return nil, false
	}
	return o.LatestDividendDate, true
}

// HasLatestDividendDate returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasLatestDividendDate() bool {
	if o != nil && !IsNil(o.LatestDividendDate) {
		return true
	}

	return false
}

// SetLatestDividendDate gets a reference to the given string and assigns it to the LatestDividendDate field.
func (o *GetStockQuoteResponse) SetLatestDividendDate(v string) {
	o.LatestDividendDate = &v
}

// GetLimitDown returns the LimitDown field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetLimitDown() string {
	if o == nil || IsNil(o.LimitDown) {
		var ret string
		return ret
	}
	return *o.LimitDown
}

// GetLimitDownOk returns a tuple with the LimitDown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetLimitDownOk() (*string, bool) {
	if o == nil || IsNil(o.LimitDown) {
		return nil, false
	}
	return o.LimitDown, true
}

// HasLimitDown returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasLimitDown() bool {
	if o != nil && !IsNil(o.LimitDown) {
		return true
	}

	return false
}

// SetLimitDown gets a reference to the given string and assigns it to the LimitDown field.
func (o *GetStockQuoteResponse) SetLimitDown(v string) {
	o.LimitDown = &v
}

// GetLimitUp returns the LimitUp field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetLimitUp() string {
	if o == nil || IsNil(o.LimitUp) {
		var ret string
		return ret
	}
	return *o.LimitUp
}

// GetLimitUpOk returns a tuple with the LimitUp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetLimitUpOk() (*string, bool) {
	if o == nil || IsNil(o.LimitUp) {
		return nil, false
	}
	return o.LimitUp, true
}

// HasLimitUp returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasLimitUp() bool {
	if o != nil && !IsNil(o.LimitUp) {
		return true
	}

	return false
}

// SetLimitUp gets a reference to the given string and assigns it to the LimitUp field.
func (o *GetStockQuoteResponse) SetLimitUp(v string) {
	o.LimitUp = &v
}

// GetLotSize returns the LotSize field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetLotSize() string {
	if o == nil || IsNil(o.LotSize) {
		var ret string
		return ret
	}
	return *o.LotSize
}

// GetLotSizeOk returns a tuple with the LotSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetLotSizeOk() (*string, bool) {
	if o == nil || IsNil(o.LotSize) {
		return nil, false
	}
	return o.LotSize, true
}

// HasLotSize returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasLotSize() bool {
	if o != nil && !IsNil(o.LotSize) {
		return true
	}

	return false
}

// SetLotSize gets a reference to the given string and assigns it to the LotSize field.
func (o *GetStockQuoteResponse) SetLotSize(v string) {
	o.LotSize = &v
}

// GetLow returns the Low field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetLow() string {
	if o == nil || IsNil(o.Low) {
		var ret string
		return ret
	}
	return *o.Low
}

// GetLowOk returns a tuple with the Low field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetLowOk() (*string, bool) {
	if o == nil || IsNil(o.Low) {
		return nil, false
	}
	return o.Low, true
}

// HasLow returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasLow() bool {
	if o != nil && !IsNil(o.Low) {
		return true
	}

	return false
}

// SetLow gets a reference to the given string and assigns it to the Low field.
func (o *GetStockQuoteResponse) SetLow(v string) {
	o.Low = &v
}

// GetNetAsset returns the NetAsset field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetNetAsset() string {
	if o == nil || IsNil(o.NetAsset) {
		var ret string
		return ret
	}
	return *o.NetAsset
}

// GetNetAssetOk returns a tuple with the NetAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetNetAssetOk() (*string, bool) {
	if o == nil || IsNil(o.NetAsset) {
		return nil, false
	}
	return o.NetAsset, true
}

// HasNetAsset returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasNetAsset() bool {
	if o != nil && !IsNil(o.NetAsset) {
		return true
	}

	return false
}

// SetNetAsset gets a reference to the given string and assigns it to the NetAsset field.
func (o *GetStockQuoteResponse) SetNetAsset(v string) {
	o.NetAsset = &v
}

// GetNetExpenseRatio returns the NetExpenseRatio field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetNetExpenseRatio() string {
	if o == nil || IsNil(o.NetExpenseRatio) {
		var ret string
		return ret
	}
	return *o.NetExpenseRatio
}

// GetNetExpenseRatioOk returns a tuple with the NetExpenseRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetNetExpenseRatioOk() (*string, bool) {
	if o == nil || IsNil(o.NetExpenseRatio) {
		return nil, false
	}
	return o.NetExpenseRatio, true
}

// HasNetExpenseRatio returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasNetExpenseRatio() bool {
	if o != nil && !IsNil(o.NetExpenseRatio) {
		return true
	}

	return false
}

// SetNetExpenseRatio gets a reference to the given string and assigns it to the NetExpenseRatio field.
func (o *GetStockQuoteResponse) SetNetExpenseRatio(v string) {
	o.NetExpenseRatio = &v
}

// GetNetValue returns the NetValue field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetNetValue() string {
	if o == nil || IsNil(o.NetValue) {
		var ret string
		return ret
	}
	return *o.NetValue
}

// GetNetValueOk returns a tuple with the NetValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetNetValueOk() (*string, bool) {
	if o == nil || IsNil(o.NetValue) {
		return nil, false
	}
	return o.NetValue, true
}

// HasNetValue returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasNetValue() bool {
	if o != nil && !IsNil(o.NetValue) {
		return true
	}

	return false
}

// SetNetValue gets a reference to the given string and assigns it to the NetValue field.
func (o *GetStockQuoteResponse) SetNetValue(v string) {
	o.NetValue = &v
}

// GetNtvSize returns the NtvSize field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetNtvSize() int32 {
	if o == nil || IsNil(o.NtvSize) {
		var ret int32
		return ret
	}
	return *o.NtvSize
}

// GetNtvSizeOk returns a tuple with the NtvSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetNtvSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.NtvSize) {
		return nil, false
	}
	return o.NtvSize, true
}

// HasNtvSize returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasNtvSize() bool {
	if o != nil && !IsNil(o.NtvSize) {
		return true
	}

	return false
}

// SetNtvSize gets a reference to the given int32 and assigns it to the NtvSize field.
func (o *GetStockQuoteResponse) SetNtvSize(v int32) {
	o.NtvSize = &v
}

// GetOpen returns the Open field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetOpen() string {
	if o == nil || IsNil(o.Open) {
		var ret string
		return ret
	}
	return *o.Open
}

// GetOpenOk returns a tuple with the Open field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetOpenOk() (*string, bool) {
	if o == nil || IsNil(o.Open) {
		return nil, false
	}
	return o.Open, true
}

// HasOpen returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasOpen() bool {
	if o != nil && !IsNil(o.Open) {
		return true
	}

	return false
}

// SetOpen gets a reference to the given string and assigns it to the Open field.
func (o *GetStockQuoteResponse) SetOpen(v string) {
	o.Open = &v
}

// GetPChRatio returns the PChRatio field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetPChRatio() string {
	if o == nil || IsNil(o.PChRatio) {
		var ret string
		return ret
	}
	return *o.PChRatio
}

// GetPChRatioOk returns a tuple with the PChRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetPChRatioOk() (*string, bool) {
	if o == nil || IsNil(o.PChRatio) {
		return nil, false
	}
	return o.PChRatio, true
}

// HasPChRatio returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasPChRatio() bool {
	if o != nil && !IsNil(o.PChRatio) {
		return true
	}

	return false
}

// SetPChRatio gets a reference to the given string and assigns it to the PChRatio field.
func (o *GetStockQuoteResponse) SetPChRatio(v string) {
	o.PChRatio = &v
}

// GetPChange returns the PChange field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetPChange() string {
	if o == nil || IsNil(o.PChange) {
		var ret string
		return ret
	}
	return *o.PChange
}

// GetPChangeOk returns a tuple with the PChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetPChangeOk() (*string, bool) {
	if o == nil || IsNil(o.PChange) {
		return nil, false
	}
	return o.PChange, true
}

// HasPChange returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasPChange() bool {
	if o != nil && !IsNil(o.PChange) {
		return true
	}

	return false
}

// SetPChange gets a reference to the given string and assigns it to the PChange field.
func (o *GetStockQuoteResponse) SetPChange(v string) {
	o.PChange = &v
}

// GetPPrice returns the PPrice field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetPPrice() string {
	if o == nil || IsNil(o.PPrice) {
		var ret string
		return ret
	}
	return *o.PPrice
}

// GetPPriceOk returns a tuple with the PPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetPPriceOk() (*string, bool) {
	if o == nil || IsNil(o.PPrice) {
		return nil, false
	}
	return o.PPrice, true
}

// HasPPrice returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasPPrice() bool {
	if o != nil && !IsNil(o.PPrice) {
		return true
	}

	return false
}

// SetPPrice gets a reference to the given string and assigns it to the PPrice field.
func (o *GetStockQuoteResponse) SetPPrice(v string) {
	o.PPrice = &v
}

// GetPe returns the Pe field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetPe() string {
	if o == nil || IsNil(o.Pe) {
		var ret string
		return ret
	}
	return *o.Pe
}

// GetPeOk returns a tuple with the Pe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetPeOk() (*string, bool) {
	if o == nil || IsNil(o.Pe) {
		return nil, false
	}
	return o.Pe, true
}

// HasPe returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasPe() bool {
	if o != nil && !IsNil(o.Pe) {
		return true
	}

	return false
}

// SetPe gets a reference to the given string and assigns it to the Pe field.
func (o *GetStockQuoteResponse) SetPe(v string) {
	o.Pe = &v
}

// GetPeTtm returns the PeTtm field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetPeTtm() string {
	if o == nil || IsNil(o.PeTtm) {
		var ret string
		return ret
	}
	return *o.PeTtm
}

// GetPeTtmOk returns a tuple with the PeTtm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetPeTtmOk() (*string, bool) {
	if o == nil || IsNil(o.PeTtm) {
		return nil, false
	}
	return o.PeTtm, true
}

// HasPeTtm returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasPeTtm() bool {
	if o != nil && !IsNil(o.PeTtm) {
		return true
	}

	return false
}

// SetPeTtm gets a reference to the given string and assigns it to the PeTtm field.
func (o *GetStockQuoteResponse) SetPeTtm(v string) {
	o.PeTtm = &v
}

// GetPreClose returns the PreClose field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetPreClose() string {
	if o == nil || IsNil(o.PreClose) {
		var ret string
		return ret
	}
	return *o.PreClose
}

// GetPreCloseOk returns a tuple with the PreClose field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetPreCloseOk() (*string, bool) {
	if o == nil || IsNil(o.PreClose) {
		return nil, false
	}
	return o.PreClose, true
}

// HasPreClose returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasPreClose() bool {
	if o != nil && !IsNil(o.PreClose) {
		return true
	}

	return false
}

// SetPreClose gets a reference to the given string and assigns it to the PreClose field.
func (o *GetStockQuoteResponse) SetPreClose(v string) {
	o.PreClose = &v
}

// GetRating returns the Rating field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetRating() int32 {
	if o == nil || IsNil(o.Rating) {
		var ret int32
		return ret
	}
	return *o.Rating
}

// GetRatingOk returns a tuple with the Rating field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetRatingOk() (*int32, bool) {
	if o == nil || IsNil(o.Rating) {
		return nil, false
	}
	return o.Rating, true
}

// HasRating returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasRating() bool {
	if o != nil && !IsNil(o.Rating) {
		return true
	}

	return false
}

// SetRating gets a reference to the given int32 and assigns it to the Rating field.
func (o *GetStockQuoteResponse) SetRating(v int32) {
	o.Rating = &v
}

// GetReturnThisYear returns the ReturnThisYear field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetReturnThisYear() string {
	if o == nil || IsNil(o.ReturnThisYear) {
		var ret string
		return ret
	}
	return *o.ReturnThisYear
}

// GetReturnThisYearOk returns a tuple with the ReturnThisYear field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetReturnThisYearOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnThisYear) {
		return nil, false
	}
	return o.ReturnThisYear, true
}

// HasReturnThisYear returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasReturnThisYear() bool {
	if o != nil && !IsNil(o.ReturnThisYear) {
		return true
	}

	return false
}

// SetReturnThisYear gets a reference to the given string and assigns it to the ReturnThisYear field.
func (o *GetStockQuoteResponse) SetReturnThisYear(v string) {
	o.ReturnThisYear = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetStockQuoteResponse) SetStatus(v string) {
	o.Status = &v
}

// GetTickerId returns the TickerId field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetTickerId() int32 {
	if o == nil || IsNil(o.TickerId) {
		var ret int32
		return ret
	}
	return *o.TickerId
}

// GetTickerIdOk returns a tuple with the TickerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetTickerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TickerId) {
		return nil, false
	}
	return o.TickerId, true
}

// HasTickerId returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasTickerId() bool {
	if o != nil && !IsNil(o.TickerId) {
		return true
	}

	return false
}

// SetTickerId gets a reference to the given int32 and assigns it to the TickerId field.
func (o *GetStockQuoteResponse) SetTickerId(v int32) {
	o.TickerId = &v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetTimeZone() string {
	if o == nil || IsNil(o.TimeZone) {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetTimeZoneOk() (*string, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *GetStockQuoteResponse) SetTimeZone(v string) {
	o.TimeZone = &v
}

// GetTotalAsset returns the TotalAsset field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetTotalAsset() string {
	if o == nil || IsNil(o.TotalAsset) {
		var ret string
		return ret
	}
	return *o.TotalAsset
}

// GetTotalAssetOk returns a tuple with the TotalAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetTotalAssetOk() (*string, bool) {
	if o == nil || IsNil(o.TotalAsset) {
		return nil, false
	}
	return o.TotalAsset, true
}

// HasTotalAsset returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasTotalAsset() bool {
	if o != nil && !IsNil(o.TotalAsset) {
		return true
	}

	return false
}

// SetTotalAsset gets a reference to the given string and assigns it to the TotalAsset field.
func (o *GetStockQuoteResponse) SetTotalAsset(v string) {
	o.TotalAsset = &v
}

// GetTradeTime returns the TradeTime field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetTradeTime() string {
	if o == nil || IsNil(o.TradeTime) {
		var ret string
		return ret
	}
	return *o.TradeTime
}

// GetTradeTimeOk returns a tuple with the TradeTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetTradeTimeOk() (*string, bool) {
	if o == nil || IsNil(o.TradeTime) {
		return nil, false
	}
	return o.TradeTime, true
}

// HasTradeTime returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasTradeTime() bool {
	if o != nil && !IsNil(o.TradeTime) {
		return true
	}

	return false
}

// SetTradeTime gets a reference to the given string and assigns it to the TradeTime field.
func (o *GetStockQuoteResponse) SetTradeTime(v string) {
	o.TradeTime = &v
}

// GetTzName returns the TzName field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetTzName() string {
	if o == nil || IsNil(o.TzName) {
		var ret string
		return ret
	}
	return *o.TzName
}

// GetTzNameOk returns a tuple with the TzName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetTzNameOk() (*string, bool) {
	if o == nil || IsNil(o.TzName) {
		return nil, false
	}
	return o.TzName, true
}

// HasTzName returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasTzName() bool {
	if o != nil && !IsNil(o.TzName) {
		return true
	}

	return false
}

// SetTzName gets a reference to the given string and assigns it to the TzName field.
func (o *GetStockQuoteResponse) SetTzName(v string) {
	o.TzName = &v
}

// GetVibrateRatio returns the VibrateRatio field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetVibrateRatio() string {
	if o == nil || IsNil(o.VibrateRatio) {
		var ret string
		return ret
	}
	return *o.VibrateRatio
}

// GetVibrateRatioOk returns a tuple with the VibrateRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetVibrateRatioOk() (*string, bool) {
	if o == nil || IsNil(o.VibrateRatio) {
		return nil, false
	}
	return o.VibrateRatio, true
}

// HasVibrateRatio returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasVibrateRatio() bool {
	if o != nil && !IsNil(o.VibrateRatio) {
		return true
	}

	return false
}

// SetVibrateRatio gets a reference to the given string and assigns it to the VibrateRatio field.
func (o *GetStockQuoteResponse) SetVibrateRatio(v string) {
	o.VibrateRatio = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetVolume() string {
	if o == nil || IsNil(o.Volume) {
		var ret string
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetVolumeOk() (*string, bool) {
	if o == nil || IsNil(o.Volume) {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasVolume() bool {
	if o != nil && !IsNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given string and assigns it to the Volume field.
func (o *GetStockQuoteResponse) SetVolume(v string) {
	o.Volume = &v
}

// GetYield returns the Yield field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetYield() string {
	if o == nil || IsNil(o.Yield) {
		var ret string
		return ret
	}
	return *o.Yield
}

// GetYieldOk returns a tuple with the Yield field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetYieldOk() (*string, bool) {
	if o == nil || IsNil(o.Yield) {
		return nil, false
	}
	return o.Yield, true
}

// HasYield returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasYield() bool {
	if o != nil && !IsNil(o.Yield) {
		return true
	}

	return false
}

// SetYield gets a reference to the given string and assigns it to the Yield field.
func (o *GetStockQuoteResponse) SetYield(v string) {
	o.Yield = &v
}

// GetYield1Y returns the Yield1Y field value if set, zero value otherwise.
func (o *GetStockQuoteResponse) GetYield1Y() string {
	if o == nil || IsNil(o.Yield1Y) {
		var ret string
		return ret
	}
	return *o.Yield1Y
}

// GetYield1YOk returns a tuple with the Yield1Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockQuoteResponse) GetYield1YOk() (*string, bool) {
	if o == nil || IsNil(o.Yield1Y) {
		return nil, false
	}
	return o.Yield1Y, true
}

// HasYield1Y returns a boolean if a field has been set.
func (o *GetStockQuoteResponse) HasYield1Y() bool {
	if o != nil && !IsNil(o.Yield1Y) {
		return true
	}

	return false
}

// SetYield1Y gets a reference to the given string and assigns it to the Yield1Y field.
func (o *GetStockQuoteResponse) SetYield1Y(v string) {
	o.Yield1Y = &v
}

func (o GetStockQuoteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStockQuoteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvgVol10D) {
		toSerialize["avgVol10D"] = o.AvgVol10D
	}
	if !IsNil(o.AvgVol3M) {
		toSerialize["avgVol3M"] = o.AvgVol3M
	}
	if !IsNil(o.Beta3Y) {
		toSerialize["beta3Y"] = o.Beta3Y
	}
	if !IsNil(o.Bps) {
		toSerialize["bps"] = o.Bps
	}
	if !IsNil(o.Change) {
		toSerialize["change"] = o.Change
	}
	if !IsNil(o.ChangeRatio) {
		toSerialize["changeRatio"] = o.ChangeRatio
	}
	if !IsNil(o.Close) {
		toSerialize["close"] = o.Close
	}
	if !IsNil(o.CurrencyCode) {
		toSerialize["currencyCode"] = o.CurrencyCode
	}
	if !IsNil(o.DerivativeSupport) {
		toSerialize["derivativeSupport"] = o.DerivativeSupport
	}
	if !IsNil(o.Dividend) {
		toSerialize["dividend"] = o.Dividend
	}
	if !IsNil(o.Eps) {
		toSerialize["eps"] = o.Eps
	}
	if !IsNil(o.EpsTtm) {
		toSerialize["epsTtm"] = o.EpsTtm
	}
	if !IsNil(o.FiftyTwoWkHigh) {
		toSerialize["fiftyTwoWkHigh"] = o.FiftyTwoWkHigh
	}
	if !IsNil(o.FiftyTwoWkLow) {
		toSerialize["fiftyTwoWkLow"] = o.FiftyTwoWkLow
	}
	if !IsNil(o.High) {
		toSerialize["high"] = o.High
	}
	if !IsNil(o.InceptionDate) {
		toSerialize["inceptionDate"] = o.InceptionDate
	}
	if !IsNil(o.LatestDividendDate) {
		toSerialize["latestDividendDate"] = o.LatestDividendDate
	}
	if !IsNil(o.LimitDown) {
		toSerialize["limitDown"] = o.LimitDown
	}
	if !IsNil(o.LimitUp) {
		toSerialize["limitUp"] = o.LimitUp
	}
	if !IsNil(o.LotSize) {
		toSerialize["lotSize"] = o.LotSize
	}
	if !IsNil(o.Low) {
		toSerialize["low"] = o.Low
	}
	if !IsNil(o.NetAsset) {
		toSerialize["netAsset"] = o.NetAsset
	}
	if !IsNil(o.NetExpenseRatio) {
		toSerialize["netExpenseRatio"] = o.NetExpenseRatio
	}
	if !IsNil(o.NetValue) {
		toSerialize["netValue"] = o.NetValue
	}
	if !IsNil(o.NtvSize) {
		toSerialize["ntvSize"] = o.NtvSize
	}
	if !IsNil(o.Open) {
		toSerialize["open"] = o.Open
	}
	if !IsNil(o.PChRatio) {
		toSerialize["pChRatio"] = o.PChRatio
	}
	if !IsNil(o.PChange) {
		toSerialize["pChange"] = o.PChange
	}
	if !IsNil(o.PPrice) {
		toSerialize["pPrice"] = o.PPrice
	}
	if !IsNil(o.Pe) {
		toSerialize["pe"] = o.Pe
	}
	if !IsNil(o.PeTtm) {
		toSerialize["peTtm"] = o.PeTtm
	}
	if !IsNil(o.PreClose) {
		toSerialize["preClose"] = o.PreClose
	}
	if !IsNil(o.Rating) {
		toSerialize["rating"] = o.Rating
	}
	if !IsNil(o.ReturnThisYear) {
		toSerialize["returnThisYear"] = o.ReturnThisYear
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TickerId) {
		toSerialize["tickerId"] = o.TickerId
	}
	if !IsNil(o.TimeZone) {
		toSerialize["timeZone"] = o.TimeZone
	}
	if !IsNil(o.TotalAsset) {
		toSerialize["totalAsset"] = o.TotalAsset
	}
	if !IsNil(o.TradeTime) {
		toSerialize["tradeTime"] = o.TradeTime
	}
	if !IsNil(o.TzName) {
		toSerialize["tzName"] = o.TzName
	}
	if !IsNil(o.VibrateRatio) {
		toSerialize["vibrateRatio"] = o.VibrateRatio
	}
	if !IsNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	if !IsNil(o.Yield) {
		toSerialize["yield"] = o.Yield
	}
	if !IsNil(o.Yield1Y) {
		toSerialize["yield1Y"] = o.Yield1Y
	}
	return toSerialize, nil
}

type NullableGetStockQuoteResponse struct {
	value *GetStockQuoteResponse
	isSet bool
}

func (v NullableGetStockQuoteResponse) Get() *GetStockQuoteResponse {
	return v.value
}

func (v *NullableGetStockQuoteResponse) Set(val *GetStockQuoteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStockQuoteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStockQuoteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStockQuoteResponse(val *GetStockQuoteResponse) *NullableGetStockQuoteResponse {
	return &NullableGetStockQuoteResponse{value: val, isSet: true}
}

func (v NullableGetStockQuoteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStockQuoteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


